### ISSUE TITLE
HACS Integration

### ISSUE THREAD

**Issue by h0jeZvgoxFepBQ2C** [alexarch21/history-explorer-card#1]
Hi,

this repo looks really cool!

But is there a way to integrate it with the HACS installer?

Thank you! ❤️

**Comment by alexarch21** [comment]
Hey,

I planned to do that sooner or later.

I would need to add some manifest files to integrate it properly into HACS. I don't use HACS myself, so I'm going to deploy a test HA install with HACS and do some integration testing. Shouldn't be too hard.

**Comment by alexarch21** [comment]
HACS integration was added with release V1.0.2. Just add this repo as a custom repository to HACS.
