### ISSUE TITLE
Improvements of data decimation possible?

### ISSUE THREAD

**Issue by emufan** [alexarch21/history-explorer-card#100]
Currently I'm looking for peaks and max values in the history. Enabled statistics with config max for this. But have data decimation enabled. Without this, I don't see the "problem".

I get e.g.

![image](https://user-images.githubusercontent.com/22775515/204464442-f9f9ea6a-d9dd-456a-90a7-09311aea2b09.png)

So, max is in August something between 5k and 6k. Then I compared with HA statistics graph.

![image](https://user-images.githubusercontent.com/22775515/204464596-e65fdd8c-b382-4f84-915f-326deb51e2fa.png)

Huh. 8k?

And yes, ~8k, if I zoom in in the history explorer card.

![image](https://user-images.githubusercontent.com/22775515/204464743-96a55087-cc33-460a-96a2-9d4899e468fa.png)

I don't know, how the standard card is calculating what to draw, but in this case it is somehow better and/or, it would be great if the history explorer card could be improved, that min and max values stay and are not deleted as in the current data decimation implementation.

If not possible, I will switch off data decimation, with the inbuild disadventages of it.

**Comment by alexarch21** [comment]
Yeah that's possible and would make sense to preserve local min/max during decimation.

In the meantime, you can turn decimation off for the respective graphs.

**Comment by alexarch21** [comment]
New optional accurate decimation mode was added to V1.0.39 with local minmax preservation. See readme under decimation !
