### ISSUE TITLE
Tooltip state text behavior

### ISSUE THREAD

**Issue by emufan** [alexarch21/history-explorer-card#101]
Until last version (v1.0.37), the behavior was, that the bar charts have shown the translated value on the bar, but the raw value on the tooltip.

![image](https://user-images.githubusercontent.com/22775515/205137434-52dc64ce-d5e3-47d8-aa16-2d293be4e55b.png)

That was more than great (and helpful for templates, automations, yaml, etc.). Unfortunately this changed now and either **both** show raw or **both** translated status (when I change stateTextMode).

Is the a config setting to get it back as it was?

Thanks and best regards

**Comment by alexarch21** [comment]
This was actually a bug (or better, an oversight) reported by someone else (#97) and I fixed it. Not always easy to please everybody lol

I guess I can make it a config switch.

**Comment by emufan** [comment]
😂 Then it was a great bug. Liked the behavior really, because the translated state was visible, but I was able to see the eaw, without having to go to HA developer tools, etc.

I think the setting is great, perhaps just the same for bar and for tooltip, but separated two settings?

**Comment by alexarch21** [comment]
You can now do this in V1.0.39, see the readme under tooltip config !
