### ISSUE TITLE
Zones color

### ISSUE THREAD

**Issue by mycanaletto** [alexarch21/history-explorer-card#104]
Hello,

I don't have the impression that it is possible to change the colors for the zones ? (timeline).

Thanks

**Comment by alexarch21** [comment]
What do you mean by zones ?

**Comment by mycanaletto** [comment]
For exemple...

![image](https://user-images.githubusercontent.com/45459269/206818114-8c5218ec-ed6a-4739-8657-9a5b8195dba1.png)

**Comment by alexarch21** [comment]
https://github.com/alexarch21/history-explorer-card#customizing-state-colors

**Comment by mycanaletto** [comment]
I have tried ...

`stateColors:
  zone.chiron: blue >> Not OK
  not_home: silver` >> OK

**Comment by alexarch21** [comment]
It's zone.**C**hiron. Case matters.

**Comment by mycanaletto** [comment]
No, not better. I had tried.

But one can think that it is anyway the entity ID that is taken into account
![image](https://user-images.githubusercontent.com/45459269/206819352-1a0aad9c-3235-485e-a046-4940b2ff7e0f.png)

**Comment by alexarch21** [comment]
I don't understand ?

**Comment by mycanaletto** [comment]
I mean neither `zone.chiron: blue` nor `zone.Chiron: blue` works.

Chiron is always in green.

**Comment by alexarch21** [comment]
Why is your entity named like your state ?

**Comment by mycanaletto** [comment]
And how should I name it to have `zone.chiron` in blue?

**Comment by alexarch21** [comment]
Ok I think I know what you mean now. The zone domain is a bit of a special case.

Try overloading the global state instead:
```
stateColors:
  Chiron: blue
```

**Comment by mycanaletto** [comment]
Oh !!!
![image](https://user-images.githubusercontent.com/45459269/206820428-5d066651-5d3d-4bcc-9051-611b26992491.png)
Verry simple ! Merci beaucoup !

**Comment by alexarch21** [comment]
Pas de soucis :)

C'est vrai que le truc avec les zones, c'est un peu un cas à part, vu qu'une zone c'est une entité, mais c'est pas elle qui contient la valeur. Faudrait que j'éssaye de trouver une approche un peu plus logique avec ça (même si la gestion des zones dans HA est loin d'être logique).
