### ISSUE TITLE
Long Term Statistics doesn't show up on HA 2012.12+

### ISSUE THREAD

**Issue by kulmegil** [alexarch21/history-explorer-card#105]
From this [discussion started at community forum](https://community.home-assistant.io/t/new-interactive-history-explorer-custom-card/369450/537?u=kulmegil).

### Problem:
Long term statistics appears to be broken on HA core 2022.12.

### Long story short:
The probable cause, as mentioned in this [developers blog post](https://developers.home-assistant.io/blog/2022/11/16/statistics_refactoring/), is a change in recorders "`recorder/statistics_during_period`" api response. In particular _**"statistic_id" field is no longer being repeated for each list item in the returned map**_.

I spinned up a v2022.11.5 system and can confirm LTS are displaying there as expected!

Below are example PM2.5 measurements from [this station](https://powietrze.gios.gov.pl/pjp/current/station_details/info/117?lang=en), last `6 months` and `week` period of time.

Results from newest core 2022.12.2:
[pl0194a_pm25-core2022.12.2-2022-12-11_22 46 37.csv](https://github.com/alexarch21/history-explorer-card/files/10203358/pl0194a_pm25-core2022.12.2-2022-12-11_22.46.37.csv)
[pl0194a_pm25-core2022.12.2-2022-12-11_22 46 45.csv](https://github.com/alexarch21/history-explorer-card/files/10203359/pl0194a_pm25-core2022.12.2-2022-12-11_22.46.45.csv)
[pl0194a_pm25-core2022.12.2-ws.json](https://github.com/alexarch21/history-explorer-card/files/10203361/pl0194a_pm25-core2022.12.2-ws.json.txt)

Compared to previous last stable version of core 2022.11.5:
[pl0194a_pm25-core2022.11.5-2022-12-11_22 43 50.csv](https://github.com/alexarch21/history-explorer-card/files/10203365/pl0194a_pm25-core2022.11.5-2022-12-11_22.43.50.csv)
[pl0194a_pm25-core2022.11.5-2022-12-11_22 45 33.csv](https://github.com/alexarch21/history-explorer-card/files/10203366/pl0194a_pm25-core2022.11.5-2022-12-11_22.45.33.csv)
[pl0194a_pm25-core2022.11.5-ws.json](https://github.com/alexarch21/history-explorer-card/files/10203367/pl0194a_pm25-core2022.11.5-ws.json.txt)

**Comment by alexarch21** [comment]
Ah this is good info. It does look like this malfunction is caused by this breaking change in the HA API. Here is a beta with a fix, would you mind trying it ?

https://raw.githubusercontent.com/alexarch21/history-explorer-card/main/history-explorer-card.js

**Comment by kulmegil** [comment]
Getting late but here are some quick results:

v1.0.39
![Screen Shot 2022-12-12 at 00 13 30](https://user-images.githubusercontent.com/570575/206934630-1084c3ea-30ae-487c-8a74-86e037c03fe4.png)

vs beta
![Screen Shot 2022-12-12 at 00 11 45](https://user-images.githubusercontent.com/570575/206934495-1fae100f-e37e-49e3-8d50-3f92fdff78f0.png)

Also the previously posted view with 4 statistics now shows more data:
![Screen Shot 2022-12-12 at 00 10 14](https://user-images.githubusercontent.com/570575/206934436-822da14e-e312-4f2b-a888-254226ff6d9a.png)

Also the "`undefined`" strings in CSV statistics export are now properly showing entity_id..

**Comment by alexarch21** [comment]
Perfect, that was it then. I will release a hotfix on HACS. Thanks for reporting this !
