### ISSUE TITLE
Auto add filtered entities to graph

### ISSUE THREAD

**Issue by joewashear007** [alexarch21/history-explorer-card#115]
Hello, 

thanks for the awesome add-on, this is much needed!

I see there is the option to `filterEntities` config options, but I was curious if there was a way to automatically add all the filter options to the graph. My use case is with the hass docker monitor add-on, I would love to chart the CPU / Memory of each of my containers. but it is annoying to have to manually add each sensor to the chart. It would be awesome to be able to take the filtered entities lists and "add all" of them to graph. 

Thanks!
Joseph

**Comment by alexarch21** [comment]
Type `*` into the entity selector field and hit `+`. This will add all entities that match the current filter(s).

**Comment by joewashear007** [comment]
Oh, that is helpful, thank you for that info!

**Comment by alexarch21** [comment]
Does this solve this issue and can it be closed ?
