### ISSUE TITLE
History In Entity History Tab

### ISSUE THREAD

**Issue by Flint1201** [alexarch21/history-explorer-card#117]
I am asking about this function, is it supposed to be? or glitch...
![image](https://user-images.githubusercontent.com/22130873/209455601-e2b77451-6890-4814-bab5-0d3b78a57782.png)
If I open the entity property dialog the history bar/graph shows up but from this addon. 

My problem is sometimes shows up original history bar/graph from HA and after a few days shows bar/graph from history explorer and it's randomly repeating.  
If I installed this addont first time, my sensors had original HA history graph/bar. The change I noticed after few days. I would like to keep history graph/bar from this modification because is interactive inside entity dialog and just better. But how can I avoid to randomly changing without any reasons.

**Comment by alexarch21** [comment]
Difficult to say with the info you provide. 

That feature needs to be explicitly enabled  as [described here](https://community.home-assistant.io/t/new-interactive-history-explorer-custom-card/369450/378). It's a per browser feature, its state is stored in your browser memory. If you change browsers or if you delete the site data in a browser, the feature will be disabled. If you use multiple browsers, you need to explicitly enable it on each browser.

If it still randomly goes on and off on the same browser and without you clearing site data, then please post the YAML configuration of your history explorer card. If you have multiple history explorer cards on your dashboards, then please mention this and post the YAML used by each of them.

**Comment by Flint1201** [comment]
Was hard to explain for me. I am sorry, my bad I did not notice you described it.  The true is I am using multiple devices where I one of them cleared cash and used HA later.  Now it makes sence. Thank you for your quick explanation :D
