### ISSUE TITLE
Evohome

### ISSUE THREAD

**Issue by marcolagerwaard** [alexarch21/history-explorer-card#121]
When I select a climate.... Sensor from my evohome system I don't get the Temperatures but only that it is on and the date.
Other temperature sensors working well.
What is it I am doing wrong?

With history explorer card

**Comment by alexarch21** [comment]
You're doing nothing wrong. Climate entities use attributes and those are not supported by this card. If you want to show an attribute, you need to create a template sensor to transform it into a state.
