### ISSUE TITLE
Feature request: "fill between"

### ISSUE THREAD

**Issue by think-nice-things** [alexarch21/history-explorer-card#122]
Hi,

very nice history graphs indeed, thanks.
Apparently fill is done currently between zero an the lines.
It would be cool if we could fill between two lines (e.g. current temperature and dewpoint like in the example image from elsewhere):

![image](https://user-images.githubusercontent.com/4885370/210620507-3b676c4b-c74c-4446-a91b-46fac3ebad9f.png)

**Comment by alexarch21** [comment]
Unfortunately this won't be on the roadmap for the foreseeable future. Sorry.
