### ISSUE TITLE
bar graph shows wrong values

### ISSUE THREAD

**Issue by think-nice-things** [alexarch21/history-explorer-card#124]
Here's another very strnage observation.
I've a sensor "QNH" which is the equivalent air pressure at sea level in hPa.
Usual values are somewhere between 980 and 1030, in the case of the example the values are between 1020 and 1030.
I added this sensor three times with yaml as shown in the screenshot.

The first line graph shows the values correctly.
The second bar graph shows values between 0 and 6 which is completely wrong.
In the third graph I set y limits to cover the maximal expectable range of 950 and 1040 and nothing is shown there at all.

Note that all three graphs use the same sensor.

Any ideas?

![image](https://user-images.githubusercontent.com/4885370/210745092-74250943-0ccd-4c49-a522-bd369925b6b5.png)

**Comment by alexarch21** [comment]
Bar graphs are used for displaying accumulated, monotonically increasing data, like energy, rainfall, etc. Wind speed is not a monotonically increasing value and the bar graph type cannot be used for this. Use line graphs instead. It's all explained in the readme under [the bar graphs paragraph](https://github.com/alexarch21/history-explorer-card#bar-graphs-for-total-increasing-entities).
