### ISSUE TITLE
Subtraction of two entities

### ISSUE THREAD

**Issue by mako777** [alexarch21/history-explorer-card#128]
Hello, I would like to make a graph that is subtraction of two entities, for example a graph that shows difference between two temperatures. Is this possible to make such a graph ?
I tried the "Custom data processing functions" but I cannot make it work, it works for one entity but not two or more.
Have a good day.

**Comment by alexarch21** [comment]
This isn't something that is planned at this time (maybe in the future). You can however get what you want by creating a template sensor that calculates the difference and then graph that.
