### ISSUE TITLE
Feature Request: log scale for y-axis

### ISSUE THREAD

**Issue by yapweiliang** [alexarch21/history-explorer-card#129]
It would be nice if y-axis could optionally have a log scale, e.g. below (electricity power consumption)

![image](https://user-images.githubusercontent.com/11950527/211421810-83ba4201-656b-417c-8d51-884d28f17eaa.png)

**Comment by PRothDC** [comment]
This would be a great feature.  Ideally, you could select between log-10 and log-2 (or maybe an arbitrary value, but those are the most common).

**Comment by alexarch21** [comment]
[Please see here](https://community.home-assistant.io/t/new-interactive-history-explorer-custom-card/369450/645) and give your feedback ! Thanks !
