### ISSUE TITLE
Request: Ability to set default zoom level (time range)

### ISSUE THREAD

**Issue by filmkorn** [alexarch21/history-explorer-card#13]
Hello,

Love this card and was wondering if there was an option to set the default zoom level through it's configuration. It currently defaults to 12h and I was hoping to set it to 6h.

Cheers

**Comment by alexarch21** [comment]
Yup that's on the roadmap for the next release !

**Comment by alexarch21** [comment]
Added to v1.0.15:

```yaml
type: custom:history-explorer-card
defaultTimeRange: 6  // show the last 6 hours when opened
```

See the readme for more info.
