### ISSUE TITLE
Feature Request: Show current entity state after the label

### ISSUE THREAD

**Issue by madface303** [alexarch21/history-explorer-card#130]
For me (and maybe some others i think/hope) it would be nice to have the actual state of the entities shown beside the label.
For example like this (as asked for in the ha forums):

![image](https://user-images.githubusercontent.com/61362651/211620238-245000cf-41f9-490c-aaaf-6c2b729790f0.png)

Doesn't really have to be configurable, just a number you can compare to the graphs, and if there also the uom is it would be fantastic.

Thanks in advance!

**Comment by alexarch21** [comment]
Added to V1.0.43.
