### ISSUE TITLE
Method to control margins when displaying only single timeline

### ISSUE THREAD

**Issue by pdileonardo** [alexarch21/history-explorer-card#131]
Enhancement

I'm trying to create a minimalist timeline graph.  

When I have only a single entity displayed (see screenshot), it seems a lot of white space is added to pad out what I'm guessing is a height minimum.  It would be great to be able to control this.  

<img width="353" alt="Screenshot 2023-01-16 at 9 05 47 AM" src="https://user-images.githubusercontent.com/17754225/212697119-e4e51be6-4465-4852-a976-324ccd37679c.png">

With the native history card, there's a lot less white space used (second screenshot), but there's no
 way to control the state colors using that.

<img width="385" alt="Screenshot 2023-01-16 at 9 12 14 AM" src="https://user-images.githubusercontent.com/17754225/212698161-f8ad35b5-a772-4cee-a83c-343cbcb20d55.png">

If there's a way that I'm missing, please advise, as I've combed the docs pretty thoroughly looking for it.

Thanks for an excellent card.  Card config below.

type: custom:history-explorer-card
cardName: test
header: hide
barGraphHeight: 50
labelsVisible: false
labelAreaWidth: 0
showUnavailable: true
uiLayout:
  selector: hide
  toolbar: hide
tooltip:
  showDuration: true
  showColorsTimeline: false
  showLabels: false
  size: compact
graphs:
  - type: timeline
    options:
      showTimeLabels: true
    entities:
      - entity: sensor.equipment_running_downstairs_main_2
stateColors:
  heatPump: magenta
  unavailable: gray
  unknown: black

**Comment by alexarch21** [comment]
The whitespace was added to accommodate the size of the tooltip you selected (you select `compact`). Try using `size: slim` under the `tooltip` key, which uses less vertical whitespace.

**Comment by pdileonardo** [comment]
Yep, that helped a lot.  Thanks for the response.  Great card.

Bought you 3 coffees.  I appreciate it.

Patrick M. DiLeonardo
+1 919-314-3710

**Comment by alexarch21** [comment]
Thanks a lot for your support, much appreciated !

Closing this issue then.
