### ISSUE TITLE
Theme and history card

### ISSUE THREAD

**Issue by zigomatichub** [alexarch21/history-explorer-card#132]
Hello alexarch21,

First thank you so much for this great card !

I'm using the theme available into HACS - [https://github.com/basnijholt/lovelace-ios-themes](https://github.com/basnijholt/lovelace-ios-themes)

Do you know if it's possible to change or update history-card code in order to have X, Y information in white text or any color that would be better to see text in a dark mode ?

Here the example:
![image](https://user-images.githubusercontent.com/60198279/213145219-43764e60-cb4e-4866-afe6-2d790ff1cbd7.png)

**Comment by zigomatichub** [comment]
I'm sorry, I see this now...

type: custom:history-explorer-card
uimode: dark

I will try.

But about Overriding the HA more info history, not sure that is possible

**Comment by zigomatichub** [comment]
It works for the card with the dark mode :)

Still about this 
![image](https://user-images.githubusercontent.com/60198279/213149079-dc1e108d-6d32-433f-8994-cc2dfbdabcac.png)

**Comment by alexarch21** [comment]
You can force dark mode in the more info panel the same way:
```
infoPanel:
  uimode: dark
```

Note that ultimately this is a bug in the theme you're using, it should set the dark mode flag itself if it uses dark colors.

**Comment by zigomatichub** [comment]
I added infoPanel into one of the history card and it works great. Thank you so much !
