### ISSUE TITLE
feature requests: 2 graphs on each other and date selection

### ISSUE THREAD

**Issue by HyGy** [alexarch21/history-explorer-card#133]
Can u please create this features:
- we can put 2 (or more) different sensors on the same graph? (for example, the outside temperature, and the inside temperature on top each other)
- can we put the same sensor twice (or more) on the same graph but with different start data (same date range is good for me), for example to compare the outside temperature for a week now and a year ago for the same week (or month, or day, etc)

**Comment by alexarch21** [comment]
> we can put 2 (or more) different sensors on the same graph? 

[Grouping multiple entities into a single graph](https://github.com/alexarch21/history-explorer-card#grouping-multiple-entities-into-a-single-graph)

> can we put the same sensor twice (or more) on the same graph but with different start data

The time code for all graphs in the card are always sync'ed. That's a fundamental design decision. You can create two independent cards on top of each other with different `defaultTimeOffset` settings, but not on the same graph.
