### ISSUE TITLE
Interactive y-axis zooming support

### ISSUE THREAD

**Issue by roger-** [alexarch21/history-explorer-card#134]
Is there a way to zoom in on the y-axis (i.e. change the y-axis limits) *interactively*? This would be useful for viewing signals with a large dynamic range.

Maybe a modifier key (e.g. ctrl) or a button could be used to switch between x- and y-axis zooming.

**Comment by alexarch21** [comment]
I tend to agree. I had situations where I would have needed a similar feature. I will think about possible approaches to this. A modifier key would be a start. Ctrl is already used for interactive range zoom.

**Comment by alexarch21** [comment]
[Please see here](https://community.home-assistant.io/t/new-interactive-history-explorer-custom-card/369450/645) and give your feedback ! Thanks !

**Comment by alexarch21** [comment]
Added to V1.0.44.

See [Y Axis scaling](https://github.com/alexarch21/history-explorer-card#y-axis-scaling) in the readme for detailed usage.
