### ISSUE TITLE
Graph Height by graph

### ISSUE THREAD

**Issue by Duke-Box** [alexarch21/history-explorer-card#135]
Hi,

I have just started to use your card and it is excellent.

Is there anyway to alter the height of the graphs on a single card individually?
I can see lineGraphHeight & barGraphHeight but these appear only to apply at the global level of the card, not at the graph level.

I have looked through docs and the forum but could not find anything.
Any help or comments appreciated.
Thanks
Mike

**Comment by alexarch21** [comment]
Only global height is possible at this time.

Maybe in a future release. I'll mark this as a feature request.

**Comment by alexarch21** [comment]
Added to V1.0.44. 

See all the way down in the [Changing the UI layout](https://github.com/alexarch21/history-explorer-card#changing-the-ui-layout) paragraph.

**Comment by Duke-Box** [comment]
Thanks, this is good.

I note from the discussions that you are looking at a y axis zoom. This is most welcome

Thank you for an excellent card

**Comment by alexarch21** [comment]
Y-axis zoom is available in V1.0.44.
