### ISSUE TITLE
Entity Selection mixed when several history card are in use

### ISSUE THREAD

**Issue by snoopfab** [alexarch21/history-explorer-card#136]
**When several history explorer cards are used the entity selection in local storage : is mixed between them.**

### Reproduction : 

1. Add on history explorer card in a lovelace view
2. select some entities in the input selection
3. save
4. Add another history explorer card  in another lovelace view
5. select some entities in the input selection
6. save
7. Go back to the first view and the selected entities are the same as the second card ...

### Analysis
When looking at the local storage , only one entry is saved as "history-explorer_card_default" and is used by both cards to populate entities

### Expected behavior

I would expect one entry per card to be used in the local storage a

Moreover the fact that the entities are stored in the localstorage of the browser imply that the entity selection is lost between different browsers (and the home assistant android application show empty selection if the configuration has been made on a desktop computer browser)

### Version used
Dekstop browser:  chrome Version 109.0.5414.119  (64 bits)
Home assistant android application :  20230110.0 - latest
Home assistant : 2013.1.7
History explorer cards installed via HACS : v1.0.43

**_Otherwise good job and thanks for this excellent card !_**

**Comment by snoopfab** [comment]
Thanks for the quick Answer!  

It now works with cardName in the configuration.
Sorry i should have looked at the documentation but i was not expecting this to need a specific configuration.

Would it be complicated to autogenerate a unique id to avoid this problem ?

**Comment by alexarch21** [comment]
It does autogenerate a unique name when you add the card over the UI.
