### ISSUE TITLE
Not working with HA 2023.2 update

### ISSUE THREAD

**Issue by ZAKhan** [alexarch21/history-explorer-card#139]
its not working with the latest update. can you please check

**Comment by alexarch21** [comment]
And what exactly doesn't work ? A few more details would be helpful here....

**Comment by ZAKhan** [comment]
HA 2023.2.1 update 

HA shows 2 errors :

1.
Not loaded in Lovelace
You have 1 Lovelace elements that are not loaded properly in Lovelace.

2.
HACS shows red box around history-explorer-card and it says not loaded

**Comment by ZAKhan** [comment]
Upgraded to HA 2023.2.2 and still the same issue

**Comment by alexarch21** [comment]
Plenty of people, including myself, run it on 2023.2 without issues.

Post your logs.

**Comment by ZAKhan** [comment]
removed it from HACS and reinstalled it. solved the issue.

Thanks
