### ISSUE TITLE
Related feature requests: scatterplot and overlap handling

### ISSUE THREAD

**Issue by Shadowex3** [alexarch21/history-explorer-card#140]
Being able to render the actual reported data points separately from lines would be a very nice progression of the current ability to show or hide unavailability. For example you could enable the points themselves, disable hiding unavailability, and then have the lines render at reduced opacity or faded color. This would help with visibility of inconsistently or infrequently reported data while also making it immediately clear what's actual reported input and what's interpolation.

Related to this when graphing things like battery voltage and other less continuous measures it's common for a bunch of lines to wind up overlapping each other. Some way of gracefully handling that would be a solid QoL improvement. For scatterplots jitter is one method although it does sacrifice a bit of visual accuracy, for lines maybe having the colors alternate during the overlapping portion.

**Comment by alexarch21** [comment]
You mean like this ? You can do this by holding SHIFT while the mouse is over the curve.

![image](https://user-images.githubusercontent.com/60828821/217335748-6d900816-3d10-432d-9a9d-fd2636d76d14.png)

I'm not sure I follow you on your second point. Could you elaborate a little what you mean by this, maybe with an image / mockup ?

**Comment by Shadowex3** [comment]
> You mean like this ? You can do this by holding SHIFT while the mouse is over the curve.

Yes, exactly, just all the time. No need to go full d3, as awesome as being able to configure various aspects based on formulas or related measures would be I'm sure that's a ton of work to develop from scratch. Just being able to set them as permanently visible would be really spiffy.

>I'm not sure I follow you on your second point. Could you elaborate a little what you mean by this, maybe with an image / mockup ?

Like how orange and blue look in [this](https://i.stack.imgur.com/ntM6y.png) (from [stackoverflow](https://stackoverflow.com/questions/40766909/suggestions-to-plot-overlapping-lines-in-matplotlib)). Additionally having datapoints visible scatterplot style would also solve the overlapping-line issue by default as long as they aren't all reporting at (or nearly) the exact same time.

**Comment by alexarch21** [comment]
> Just being able to set them as permanently visible would be really spiffy.

I agree. That should be trivial to add. There are going to be some changes to the function in the next version anyway, due to the additional of interaction Y-axis modifications. So adding a permanent on (and permanent off) toggle should be doable.

> Like how orange and blue look in [this](https://i.stack.imgur.com/ntM6y.png)

Wouldn't it be enough to give lines a slight transparency to visually deal with overlaps ?

**Comment by alexarch21** [comment]
V1.0.44 now has a feature you can use to force visible samples on graphs. Check out [the chapter](https://github.com/alexarch21/history-explorer-card#displaying-individual-samples) in the readme.
