### ISSUE TITLE
FR: Set reference when zooming

### ISSUE THREAD

**Issue by wormiedk** [alexarch21/history-explorer-card#149]
It would be great with an option to keep the right side of the graph when zooming instead of zooming in the middle.

As en example I often open a graph and want to see more detail so I zoom in but then I see the middle of the graph, however I am mostly interested in the new data to I have to scroll all the way to the right.

**Comment by alexarch21** [comment]
Try using Ctrl-mousewheel to zoom. It will use your current mouse position as the reference.

**Comment by wormiedk** [comment]
Great :) any tips for touchdown screen?

**Comment by alexarch21** [comment]
Not at this time. Maybe pinch-to-zoom may come in a future release.

I'll mark this as a FR. I may add a setting in a future release.
