### ISSUE TITLE
X axis range

### ISSUE THREAD

**Issue by vmonkey** [alexarch21/history-explorer-card#151]
Hi, first of all thanks for a wonderful card! I have one small question/request. Is there a way to dynamically enforce (initial) limits on the graph time axis?

My use case: torque integration collecting drive data. I would like to plot graphs for the last drive. I would be able to write sensors storing the start and ending times of the drive, I would love to use these as limits of the time axis.

Many thanks!

**Comment by alexarch21** [comment]
If you mean initial limits as in showing the relevant range by default, check out the `defaultTimeRange` and `defaultTimeOffset` settings. If you mean hard limits preventing the user from scrolling out of boundary, then no, I'm afraid there is no such feature.

**Comment by vmonkey** [comment]
Thanks. In a sense, this is what I need. Now, is there a possibility to set defaultTimeRange and defaultTimeOffset dynamically, i.e., based on a sensor value/javascript function, e.g., something like this (does not work)?

defaultTimeRange: |
  [[[
      return (parseFloat(states['sensor.trip_time_since_journey_start'].state)/60).toFixed(0) + 'm';
  ]]]
defaultTimeOffset: |
  [[[
      var now = new Date();
      var old = (new Date(states['sensor.trip_time_since_journey_start'].last_changed));
      var rem = Math.floor((old.getTime() - now.getTime()) / 60000);
      return rem + 'm';
  ]]]

**Comment by alexarch21** [comment]
They're fixed parameters, I'm afraid. At least for now.

I wonder if you could use something like card-mod to generate the YAML on the fly ? Not too sure if it can do that.

**Comment by vmonkey** [comment]
Many thanks. I have some progress by combining your card with custom-buttom-card. It works almost as expected but there is still one issue I need to solve - some elements in the history-explorer card do not (line)-break as they do in the standalone card. If I fix this, I will also post this here for future reference. 

![Snímek obrazovky z 2023-03-06 20-44-31](https://user-images.githubusercontent.com/770524/223214485-11e188f1-4bd5-4517-8df0-ef3649043417.png)

Test YAML
type: custom:button-card
tap-action: none
custom_fields:
  graph:
    card:
      type: custom:history-explorer-card
      header: hide
      combineSameUnits: true
      refresh:
        automatic: true
      showCurrentValues: true
      uiLayout:
        selector: hide
        toolbar: bottom
        interval: hide
      graphs:
        - type: line
          entities:
            - entity: sensor.speed_obd
              name: Rychlost
      defaultTimeRange: |
        [[[
          return (parseFloat(states['sensor.trip_time_since_journey_start'].state)/60).toFixed(0) + 'm';
        ]]]
      defaultTimeOffset: |
        [[[
          var now = new Date();
          var old = (new Date(states['sensor.trip_time_since_journey_start'].last_changed));
          var rem = Math.floor((old.getTime() - now.getTime()) / 60000);
          return rem + 'm';
        ]]]
      style: |
        ha-card {
          box-shadow: none;
        }
styles:
  custom_fields:
    graph:
      - overflow: auto
      - padding: 0%
  card:
    - overflow: auto
    - padding: 0%
    - position: relative
