### ISSUE TITLE
[Feature Request] Rolling timeline/x-axis

### ISSUE THREAD

**Issue by habitoti** [alexarch21/history-explorer-card#152]
Please provide an option to have the x-axis constantly show a configurable interval of the timeline back from "now". The timeline display should then update in real-time (or configurable intervals, respectively), so that it rolls along and always show "now" as the rightmost point in time.

- If the timeline is changed interactively, this automatic "current interval" mode stops
- This stopped auto-update mode can be restarted by choosing an according mode explicitly again from interval selector
- When choosing a future point in time as rightmost timestamp, data will fill up statically until that point is reached, and then timeline starts to autoscroll.

**Comment by alexarch21** [comment]
Good idea !

**Comment by alexarch21** [comment]
Added to V1.0.45.
