### ISSUE TITLE
HA Companion App (beta) scrolls to top of page after chart zoom 

### ISSUE THREAD

**Issue by dimitrior** [alexarch21/history-explorer-card#155]
Hi,
In the HA app, after I click the zoom button and select a region on the chart, if I'm on a view where the HE card is more than a screen from the top of the page, the page is scrolled to the top of the view. On Android 13, HA app beta-3200-4b22c2b4-full. 
I just remembered I'm on beta, maybe that's it....

**Comment by alexarch21** [comment]
Please test on non-beta release.

**Comment by dimitrior** [comment]
Thanks @alexarch21 . I will, but since I cannot promise when, I will close this and open anew if needed in future.

**Comment by dimitrior** [comment]
See last comment
