### ISSUE TITLE
Export CSV doesn't export selected date range

### ISSUE THREAD

**Issue by shayaknyc** [alexarch21/history-explorer-card#158]
Hey y'all, wondering if someone can shed some light on an issue I'm having specifically on exporting to CSV. I have a sensor that's measuring air quality metrics (specifically TVOCs) over the course of a few months. I came to History Explorer Card to help me export some date ranges of collected readings. I've tried a week, I've tried a month, I've tried 3 months, and each export is exported with a seemingly random date range, that does not reflect the date range selection in the history card.

I'm running Home Assistant 2023.3.2
Supervisor 2023.03.1
Operating System 9.5
Frontend 20230306.0 - latest

And history-explorer-card v1.0.44. 

Even when I have the date range indicate 3 months from "today" or 1 week from "today" it shows 26 Feb through 1 Mar. I've tried 3 months since 31 Jan, and that still exports a static date range. I'm attaching a recent export, set for 3 months from today. Any ideas?

Edit: added attachment
[entities-2023-03-09_14_33_08.csv](https://github.com/alexarch21/history-explorer-card/files/10935356/entities-2023-03-09_14_33_08.csv)

**Comment by alexarch21** [comment]
Are you sure you are using 'Export *statistics* as CSV' ? Not 'Export as CSV'.

**Comment by shayaknyc** [comment]
I am NOT using Export Statistics, I am using Export CSV. I need the raw values saved in the history, Export Statistics does seem to respect the date range, but the values are not useful to me. See attached.
[entities-2023-03-09_14_45_47.csv](https://github.com/alexarch21/history-explorer-card/files/10935457/entities-2023-03-09_14_45_47.csv)

**Comment by alexarch21** [comment]
Export CSV (without statistics) will only go as far as your history database does. It can't export something that is not in the database. By default that is 10 days, unless you changed `purge_keep_days` in your recorded settings.

**Comment by shayaknyc** [comment]
First of all, Export Statistics CSV DOES export the date range, just not the raw values. Secondarily, Home Assistant does have the data as far back as Nov 2022, I effectively need the data specifically from Jan 21, 2023 - March 8, 2023, so 3 months back from March 8, 2023 will give me more than I need, and I can just cull the rows that are unnecessary. The problem is that it's only going as far back as Feb 27. Even when I export 1 week, it still spits out from Feb 27, which is also weird.

**Comment by alexarch21** [comment]
> First of all, Export Statistics CSV DOES export the date range, just not the raw values.

It exports exactly what it finds in the database. Nothing more and nothing less. The statistics database does not contain 'raw values'. It contains hourly, daily and monthly mean, max and mins. That's it. There's nothing more to export, because there's nothing more stored in the statistics DB.

>  Secondarily, Home Assistant does have the data as far back as Nov 2022,

In the statistics. Unless you have specifically set your actual history DB (which is separate from the statistics) to keep 3 months worth of data by setting `purge_keep_days`. If you did not do that, your history DB will only keep 10 days of 'raw values'. That's the HA default.

**Comment by shayaknyc** [comment]
But I'm able to literally pull up raw values older than 10 days both through the default History functionality and through History Explorer Card

**Comment by alexarch21** [comment]
The history explorer card will combine statistics and history on the fly. It will use statistics (the mean value) when history is unavailable for the requested range.

The normal history only goes back as far as the recorder component is configured for. If you didn't change `purge_keep_days` then that is 10 days. Anything beyond that is statistics.

**Comment by shayaknyc** [comment]
I have configured `purge_keep_days` for longer, since I am able to pull a SQL query to get those values, I just found your card to be A LOT easier.....

**Comment by alexarch21** [comment]
So how far have you configured it then ? You need to provide more info in order to get help.

**Comment by shayaknyc** [comment]
365 days

**Comment by alexarch21** [comment]
What ?! That is waaaay out of the specifications of any HA install I have ever seen or tried. People will usually get problems from 30+ days, 90 days is the absolute maximum I have ever heard someone using. I'm afraid I can't help you with that. There is no way I can even test this.

**Comment by alexarch21** [comment]
Alright, let me explain that a little more. You'll have to excuse my surprise on the previous message, your values are just so far off the scale... You are 36 times above the recommended value for that setting.

So what I *think* is happening is that the HA history REST API can't return that much data in a single call. The card itself works by loading in smaller chunks, so that works. The CSV export does a single call. But there is no way I can test this hypothesis. 

Now the next version of the card will switch from using the REST API to the newer WS API to get history, mostly for performance reasons. The builtin HA history already does this. As the WS API is more advanced and can transfer a lot more data more easily, this could fix your problem as a side-effect. Maybe. Would certainly be an interesting experiment ;)

**Comment by shayaknyc** [comment]
I only have the one sensor, there's nothing else being collected by HA. I've also only been running this since the end of November, so there isn't an overwhelming amount of data collected there. Happy to wait until the next update to see if that solves the issue :) Thanks!

**Comment by alexarch21** [comment]
As mentioned, I can't promise that it will fix the issue. You have a highly unique case and by pushing the limits of HAs database engine so far out of its normal limits, you're prone to run into weird corner case behavior here and there.

**Comment by shayaknyc** [comment]
Yeah, worth a shot, considering I only have effectively 3 months' worth of data, figured I'd try. The SQL query does produce the data, but then I have to do more to process it in a way that I need, and I found your card to be extremely helpful. Looking forward to the the next update!

**Comment by alexarch21** [comment]
Alright then. I'll close this and you can try again with the next release.

**Comment by q20** [comment]
> What ?! That is waaaay out of the specifications of any HA install I have ever seen or tried. People will usually get problems from 30+ days, 90 days is the absolute maximum I have ever heard someone using. I'm afraid I can't help you with that. There is no way I can even test this.

Hey could you link to documentation indicating 365 days is out of spec? SQLite.org's docs state their database will scale to 281 TB. Which is quite large.

I'm not suggesting it'll be _fast_, but storing data for 365 days, would require logging the thick end of 1 TB daily to approach 281 TB.
