### ISSUE TITLE
Y axis labels

### ISSUE THREAD

**Issue by bbigoss** [alexarch21/history-explorer-card#159]
Hi,
is it possible to put some random numbers onto y label? For ex. with temp sensor I have temp in every 10 degree, but for better visual  control is to have some specific degrees like 2,6,15 or similar. I tried to give some "yLabel" but it doesn't work.

**Comment by alexarch21** [comment]
No that's not possible.

**Comment by bbigoss** [comment]
ok, thx for reply @alexarch21
