### ISSUE TITLE
hide entity in graph by default - command ?

### ISSUE THREAD

**Issue by mihmihmih1988** [alexarch21/history-explorer-card#160]
Any command i can use in YAML to hide an entity in graph by default ?
Could not find it in the manual.

Great card by the way !

![image](https://user-images.githubusercontent.com/127425565/224544042-99a7650c-eee8-4596-bbc1-4d885de315a2.png)

**Comment by alexarch21** [comment]
No there's none. I can mark this as a Feature Request though.

**Comment by mihmihmih1988** [comment]
that would be fantastic...

**Comment by alexarch21** [comment]
Now available in V1.0.45. See the advanced YAML example at the end of the readme for an example.
