### ISSUE TITLE
FR: set time offset for an entity

### ISSUE THREAD

**Issue by plee3001** [alexarch21/history-explorer-card#164]
The history explorer card is great. Thanks.

Is there a way to set a time offset for a specific entity? A possible use case would be to add the same entity twice, one with the offset. That would give a good visualization of the differences between the time offset.

**Comment by alexarch21** [comment]
Right now, no. You can do it per card using `defaultTimeOffset` and have two stacked cards, but it's not supported per entity.

I'd like to have this feature myself for my own use too. So it's likely to be implemented at some point in the future (basically when I get around to do it).

**Comment by alexarch21** [comment]
Sadly the history explorer card has been declared end of life and won't be developed anymore. So I will have to close this issue / FR without resolution. This repository will be archived and set to read-only shortly.

See this post on the HA forum for more information: 

https://community.home-assistant.io/t/new-interactive-history-explorer-custom-card/369450/978
