### ISSUE TITLE
Card name won't change

### ISSUE THREAD

**Issue by Caddyman68** [alexarch21/history-explorer-card#166]
Maybe (probably) I'm doing something wrong or expecting something incorrectly. I use the line "cardName: xxxx" as the second in my yaml but it doesn't change "History explorer" to "xxx". I tried redownloading in HACS and of course reloading. I can only see 2 possibilities: I have a corrupt (??) add-on or the name of the card doesn't default to "History explorer" and thus that doesn't change to "xxx" - but I don't see anything else.
It seems like something simple and I could possibly live with it - the card itself has a lot of options I really like and I appreciate the time spent by the developer(s)

Edit: I guess it isn't possible to change the title "History explorer" on the individual cards (cardName is only to organize them/ differentiate them). If it is, I'd like to know how; if it isn't there should be a feature request IMHO.

**Comment by alexarch21** [comment]
[Header text](https://github.com/alexarch21/history-explorer-card#header-text) in the readme.

**Comment by Caddyman68** [comment]
I coulda swore I searched the whole readme, but obviously I didn't or perhaps just missed it. I remember seeing the CSV option - main reason I got the addon. There are TONS of options. Thanks alexarch21.
