### ISSUE TITLE
Not loading

### ISSUE THREAD

**Issue by vojky-gmx** [alexarch21/history-explorer-card#169]
Running on clean HASS OS on Pi 4. Won't load.
Was loading on QNAP HASS container
![no-load](https://user-images.githubusercontent.com/106708800/234186552-3b694c6a-5f39-42a2-b5ca-a91fc15a6c8b.jpg)

**Comment by vojky-gmx** [comment]
[home-assistant_2023-04-25T19-32-25.631Z.log](https://github.com/alexarch21/history-explorer-card/files/11326151/home-assistant_2023-04-25T19-32-25.631Z.log)

**Comment by alexarch21** [comment]
That's a HACS log entry. It has nothing to do with this card.

**Comment by vojky-gmx** [comment]
I set logger to debug and rebooted the Pi. Hope this helps
![HACS](https://user-images.githubusercontent.com/106708800/234400897-a48da121-c669-4384-87b9-180560ab8eff.jpg)
[home-assistant_2023-04-25T20-50-50.045Z.log](https://github.com/alexarch21/history-explorer-card/files/11326788/home-assistant_2023-04-25T20-50-50.045Z.log)

**Comment by alexarch21** [comment]
There is no information about the history explorer card in your logs, the cards code didn't even start. This is an issue with HACS or with the way the resource was installed (or _not_ installed for that matter). [See here](https://hacs.xyz/docs/faq/status_not_loaded/).

I'm afraid I can't help with this, as it isn't related to the card. I suggest you post this on the HA forums, someone with more insight into HACS may be able to help.

**Comment by vojky-gmx** [comment]
Hi,

Working no after the update. Thanks
