### ISSUE TITLE
Graph expanding till it causes app crash when adding first entity on android app

### ISSUE THREAD

**Issue by robertboccia** [alexarch21/history-explorer-card#17]

**Comment by tht** [comment]
Same issue on Safari 15.3 on macOS. It slowly grows… I closes the navigated away before anything crashed ;).

**Comment by alexarch21** [comment]
Wow yeah, was able to reproduce this on our Mac in the office. Will fix this asap when I get home.

**Comment by alexarch21** [comment]
Hotfix released on V1.0.16 that should hopefully fix this. Could you guys confirm that this addresses the issue ?

**Comment by tht** [comment]
Solves the issue for me in Safari on macOS. Thanks!

**Comment by robertboccia** [comment]
Fixed on android, but now seems you can't scroll the graph with touch

Robert Boccia
________________________________
