### ISSUE TITLE
Bar chart mode

### ISSUE THREAD

**Issue by Algol655** [alexarch21/history-explorer-card#170]
Hi Alex. After understanding what you meant by FR, I renew the request here. 
I would like the "bar graph" mode to be added to the current modes (curves, lines, stepped, bar), showing the absolute values of the entities.
It would also be useful to display the value of the entity inside the bar, as shown in the example.
Obviously all the axis selection, scrolling and zooming features of the existing modes should be retained.
Thank you for your great work and greetings
Tommaso
![BarChart_Example](https://user-images.githubusercontent.com/112681151/235859101-bc88944f-5578-441b-b6a4-fbe7097e4990.jpg)

**Comment by alexarch21** [comment]
Note that this FR is more than just a bar graph visual. There's data processing and a UI involved too. Unless your entity updates one single time per day at exactly midnight, on the fly resampling (average, min, max) will be needed. There also needs to be a UI element to choose the time interval represented by each bar, similar to the one the current total_increasing bar chart uses and possibly one to choose the resampling metric (mean/min/max/etc).

To be honest with you, considering the amount of work involved to do this right and the fact that this is a niche feature, this won't be very high priority. Sorry. 

I'll mark this as an enhancement request for now.

**Comment by Algol655** [comment]
Hi Alex, I realize it's not an easy job.
However, no processing of the data should be done: the values transmitted are already the maximum values of the daily averages (values of gaseous pollutants) and they are transmitted only once a day, precisely, at midnight.
What would currently be useful for me is "only" to view this data, day by day, as a bar graph. All the mathematical processing is done by the transmitting node.
I hope this can be a simplification of the development.
Greetings

**Comment by alexarch21** [comment]
But this makes this feature even more unique to your specific case. In order for such a feature to make sense, it should be more generic, so that users with more standard setups can also use it. While this feature would indeed be more simple to implement for your situation, it is also a very uncommon one. Most people would just have the unprocessed data with multiple samples per time interval.

**Comment by Algol655** [comment]
Alright Alex, I understand.
I was convinced that a bar graph mode displaying the absolute values of entities, albeit with some limitations, could be of general interest.

**Comment by jtkacz** [comment]
I fully support FR by @Algol655. Bar graph is proper way of visualization i.e. for hourly prices of energy.

**Comment by alexarch21** [comment]
Unless someone comes up with a PR implementing this, I'm afraid this feature isn't planned at this time. Maybe in the future.
