### ISSUE TITLE
More default colors

### ISSUE THREAD

**Issue by MortenHannemose** [alexarch21/history-explorer-card#174]
Thanks for an amazing plugin.
It would be nice if there was more than five default colors for when you add many things to a graph.
There is a website that has many easily distinguishable colorschemes.
I would suggest the following with nine different colors: 
https://colorbrewer2.org/?type=qualitative&scheme=Set1&n=9
![image](https://github.com/alexarch21/history-explorer-card/assets/11504118/e136e02b-eec4-4e01-97dc-313285c3bcf2)

Let me know if you would be interested in a PR for this.

**Comment by alexarch21** [comment]
Adding more colors is a good idea, it actually became necessary while adding wildcard support to the card (as this could mass-add entities into single graphs). I would not want to change the current colors at all, nor their order. People grow accustomed to things like this and changing them will mess up some setups. But I'd like to add some more. The site you linked to is interesting, thanks for posting it. I'll look into this on the weekend and let you know if a PR is needed or if I just end up copy and pasting some additional colors is.

**Comment by alexarch21** [comment]
V1.0.47 has some more default colors now. Thanks for the idea !
