### ISSUE TITLE
Stopped working?

### ISSUE THREAD

**Issue by JonLaliberte** [alexarch21/history-explorer-card#176]
Anyone else have issues since 2023.5?
I’ve tried clearing cache and tried reinstalling the card with no luck.

**Comment by JonLaliberte** [comment]
I take it back! I was most used to using this as [a replacement for the default history panel](https://community.home-assistant.io/t/new-interactive-history-explorer-custom-card/369450?page=19), but that must have got reset along the way. 

On that note is there a way to store this setting so it stays enabled?

**Comment by alexarch21** [comment]
> On that note is there a way to store this setting so it stays enabled?

I'm not sure what you mean by this. This setting is stored in your browser and it stays enabled as long as your browser keeps it (ie. it is removed if you clear the local site data).

**Comment by JonLaliberte** [comment]
I wasn't sure if it would be possible to have that setting set globally (for all clients connecting to the HA instance).

**Comment by alexarch21** [comment]
Technically not possible, I'm afraid (HA does not give frontend cards write access to the backend config).
