### ISSUE TITLE
Bar graph with negative bars

### ISSUE THREAD

**Issue by bakerkj** [alexarch21/history-explorer-card#177]
I'd like to be able to display net electricity usage in a bar graph (similar to the energy dashboard in home assistant). I've added the appropriate sensor (state_class: total) to a history explorer card with "type: bar". Everything works as expected until the usage is negative (my solar panels are pushing power to the grid) at these times the bar is zero (instead of negative).

Thanks!

**Comment by bakerkj** [comment]
@alexarch21 yeah, I am using state class 'total' sensor which can go up and down.

Thanks for the suggested work around splitting it into a pair of total_increasing sensors. I'll have to give it a try.

Thanks.

**Comment by alexarch21** [comment]
The state class total is not supported by the card (maybe in a future version, the changes required to support it would be minimal). The bar type only supports total_increasing, as noted in the readme.

I'm closing this for now, feel free to post on the HA forum thread if the workaround doesn't work. You can also open a FR for the future support of the total state class if you want. I'm not sure how many people actually use this class (net metering is less and less common), but it would be easy to add.

**Comment by alexarch21** [comment]
V1.0.47 added net metering support for bar graphs. [See here](https://github.com/alexarch21/history-explorer-card#net-metering).

**Comment by bakerkj** [comment]
@alexarch21 thank you!
