### ISSUE TITLE
FR: UI-option to switch to line graph for total increasing entities

### ISSUE THREAD

**Issue by emufan** [alexarch21/history-explorer-card#178]
Sometimes (here often) I would like to see a old school line graph even for total increasing entities, esp. to see unavailability, jumping of values, etc. which is hard or not possible to see with the sum-bars, which are of course helpful in other cases.

A "simple" 😂 switch in the UI to switch from sum-bars to line (visa versa) in such cases of total increasing entities would be very appreciated. 

Another idea: Have a separate value "non combined" in the dropdown to switch to line:

![image](https://github.com/alexarch21/history-explorer-card/assets/22775515/bca457a6-a29d-43c7-85f6-836377d563bb)

**Comment by alexarch21** [comment]
Been on the backlog for a while now. It would go into the dropdown, probably as an entry called 'raw data' or something like this. It should also be possible to hide this entry.

It's not completely trivial as it changes graph types internally, but I can see if I can sneak that in when adding weekly bars in the next release.

**Comment by emufan** [comment]
Would be more than great. :-)

**Comment by alexarch21** [comment]
Will be available in 1.0.47 coming this weekend:

![image](https://github.com/alexarch21/history-explorer-card/assets/60828821/5f4ebd57-1c69-44ec-956e-a7930d52e130)

![image](https://github.com/alexarch21/history-explorer-card/assets/60828821/657383d7-fd75-4d85-ae65-c11f2e587629)

**Comment by emufan** [comment]
Wonderfull!

**Comment by alexarch21** [comment]
It's in V1.0.47.
