### ISSUE TITLE
Allow Line to be disabled by Default

### ISSUE THREAD

**Issue by pos-ei-don** [alexarch21/history-explorer-card#179]
I have a set of Grapfs, ans some minor (more detailed) lines configured.

I'd like to show some of them per default as disabled (like when you click per mouse on it!).
I just need to enable these if i see a problem and want to analyse it more deeply.

**Comment by alexarch21** [comment]
`hidden: true`

[It's in the readme.](https://github.com/alexarch21/history-explorer-card#grouping-multiple-entities-into-a-single-graph)

**Comment by pos-ei-don** [comment]
Sorry, I really search the readme, but did not find or at least understand that hidden exiats and that it works like this. Sorry and thank you a lot!
