### ISSUE TITLE
Request: Can we zoom-in deeper than 1 hour?

### ISSUE THREAD

**Issue by QbaF** [alexarch21/history-explorer-card#18]
Most HA charts have the disadvantage that are not able to show a time range shorter than 1 hour. And sometimes we look for fast-changing states where an hour resolution is not enough.

Is there a chance that we will be able to zoom deeper - in minutes or even seconds?
And could be there a possibility to set an initial time range in minutes or seconds??

**Comment by alexarch21** [comment]
Added to V1.0.17, you can now zoom into the data up to a range of 1 minute.
