### ISSUE TITLE
FR: Space between (Timeline) Graphs more Compact (see HA-History Card)

### ISSUE THREAD

**Issue by dafunkydan** [alexarch21/history-explorer-card#181]
I really would love to replace my (static) HA History Cards with the Lightyears better History Explorer Card - but as it takes around 30-40% more Vertical Space, this isn't really a good trade - specially for mobile Layouts.

It would be great to adjust Height of, and Space between, Timeline Graphs!

And, while the HA History Card comes with an Option "Hours to display", it would be awesome if History Explorer Card would be capable of this as well - by now it has 10m, 1h, 1d, 1m.

![grafik](https://github.com/alexarch21/history-explorer-card/assets/103875104/56e4cc51-ec66-4bec-8aba-c95822cea2b0)

**Comment by alexarch21** [comment]
About the spacing, this is so that there is enough space for the tooltip. You can reduce spacing by using a smaller tooltip. See here: 
https://github.com/alexarch21/history-explorer-card/issues/131

> And, while the HA History Card comes with an Option "Hours to display", it would be awesome if History Explorer Card would be capable of this as well - by now it has 10m, 1h, 1d, 1m.

I'm not sure I understand. Could you clarify this ? You can display as little or as much by default as you want. From the readme:

> When the dashboard is opened, the card will show the last 24 hours by default. You can select a different default time range in the YAML. Use m, h, d, and w to denote minutes, hours, days and weeks respectively. For longer time scale, o and y denote months and year. Currently the maximum range is one year. If no postfix is given, hours are assumed.
> 
```
type: custom:history-explorer-card
 defaultTimeRange: 4h     # show the last 4 hours when opening the card
 defaultTimeRange: 2d     # or 2 days...
 defaultTimeRange: 15m    # or 15 minutes...
 defaultTimeRange: 3w     # or 3 weeks
 defaultTimeRange: 6o     # or 6 months
 defaultTimeRange: 1y     # or 1 year
```

**Comment by dafunkydan** [comment]
> You can display as little or as much by default as you want. From the readme:

Oh no :-( My Bad, so sorry. Sure that works. I mixed it up with:
`     interval: 10m     # Default interval for this entity can be 10m, hourly, daily or monthly.`


> You can reduce spacing by using a smaller tooltip. See here: https://github.com/alexarch21/history-explorer-card/issues/131

This unfortunatly doesn't work. The Tooltip does change between slim/compact/full, depending on what i put in, but the Timeline Bar/Space between them doesn't get smaller. 

I am not sure wether this really adresses the _Space between_ the Timelines? The Entry you referenced is talking about "for when _displaying only single timeline_". I am pretty sure i do something wrong - but i have no clue what i am missing :-(

![grafik](https://github.com/alexarch21/history-explorer-card/assets/103875104/353cba94-c7f3-4b0a-bd17-ebde8f9e6541)
As the Code
```
tooltip:
  size: slim
```
does change the Tooltip, i refrain from posting the whole Code

**Comment by alexarch21** [comment]
There's no way to change the spacing between multiple stacked timelines at this time I'm afraid.

**Comment by dafunkydan** [comment]
Yes, that is what i was already thinking - i just wanted to make you aware of this FR.
Sometimes such Things are easy to implement, already on the Bucketlist, whatever :-) Just wanted to let you know. And maybe someday it might find its Way into that really awesome Project!

**Comment by dafunkydan** [comment]
Personally i would love to see that Feature. If it is a matter of a few Lines, while already inside the Code - sure, i'd really appreciate it!

**Comment by alexarch21** [comment]
This is going to be available in the upcoming 1.0.47. You'll be able to control both the timeline bar height and the spacing.

![image](https://github.com/alexarch21/history-explorer-card/assets/60828821/e36787a5-ee1f-4e65-af9a-3157fa673c6d)

**Comment by dafunkydan** [comment]
Thats some awesome News! Didn't really expect it to find its way soon, if at all. Great, can't wait, Thank you so much!

**Comment by alexarch21** [comment]
V1.0.47 is out

Example YAML:
```
type: custom:history-explorer-card
timelineBarHeight: 18    # timeline bar height (default is 24)
timelineBarSpacing: 30   # spacing from the top of one timeline bar to the next (default is 40)
```
Don't make them too small or weird rendering bugs may appear.

**Comment by dafunkydan** [comment]
Works great, Thank you again so much!

I found out, it only works if
```
type: custom:history-explorer-card
  tooltip:
    size: slim
```
is set. Which makes sense and is totally fine, but is good to know though ;-)
Thanks again! You have an awesome Project!

**Comment by alexarch21** [comment]
It works with all sizes of tooltips, but each tooltip mode will force a minimum size on the entire timeline graph, according to its own size, so that it isn't clipped away.
