### ISSUE TITLE
Set interpolation to step for default entity history

### ISSUE THREAD

**Issue by ast0815** [alexarch21/history-explorer-card#182]
Hello,

looks like history-explorer-card is now replacing the default entity history when clicking on an entity in a dashboard. Unfortunately the default interpolation mode seems to be `lines`. This really messes up graphs of entities with long times of constant values. E.g. see my fridge power consumption wich should be exactly 0 for long stretches of time and then jump up. Instead I get triangles now:

![image](https://github.com/alexarch21/history-explorer-card/assets/5884065/36ad1850-4837-44df-b6f8-77f59dbd9da3)

Is there a way to configure these default history plots? Did not see anything in the README.

**Comment by ast0815** [comment]
Maybe another question is whether it is possible to switch this replacement off, because the vanilla graphs are more readable at the moment.

**Comment by alexarch21** [comment]
Yes the interpolation can be set to stepped and yes it can be turned off. All of this is explained in the readme and in the HA forum thread linked in the readme. I suggest you take a quick look there.
