### ISSUE TITLE
Option to hide dynamic addition of sensors/export

### ISSUE THREAD

**Issue by Elarion245** [alexarch21/history-explorer-card#184]
Hello,

I like the card a lot and use it in two way:
1) To plot data (I often find it nicer-looking than plotly-graph)
2) As a dashboard to export into csv

In case of the first use, I only want the plot as preconfigured using yaml. In case of the second I only add one or two and export the data.
-> I would appreciate an option to hide the dynamic sensor addition bar in yaml, such that this option is not taking unnecessary space in my cards.

Thank you!

**Comment by alexarch21** [comment]
```
uiLayout:
  selector: hide
```

[It's all in the readme.](https://github.com/alexarch21/history-explorer-card#changing-the-ui-layout)

**Comment by Elarion245** [comment]
Thanks! I've tried it while editing the card, and then gave up as it did not change the preview, but in fact I only had to press Save for it to update.

Great card!
