### ISSUE TITLE
Export CSV file while also having "selector": "hide"

### ISSUE THREAD

**Issue by philwingfield** [alexarch21/history-explorer-card#185]
Hi,

I have a graph where the entities are pre-selected in the config and I don't show the entity selector. This means I can't get to the "Export as CSV" option. At the moment I have to edit the config, restart HA, get the CSV and then change it back again.

I do have a workaround and this maybe is a niche issue, but if you are in that area of the code it would be nice to move the "Export as CSV" option under a different menu so I can get to it in my use case.

Love the addon, you are doing great work thank you!

Thanks,

Phil

**Comment by alexarch21** [comment]
Moving the option depending on toolbar visibility is not something that is planned at this time, I'm afraid. Sorry.
