### ISSUE TITLE
Custom element does not exist

### ISSUE THREAD

**Issue by Serhioromano** [alexarch21/history-explorer-card#187]
I have latest HAS and latest card. It works fine on my PC web browser but do not work in HAS mobile app. Shows this error. I made search and tried to apply few options but none of them was successful.

**Comment by alexarch21** [comment]
Can't reproduce. Make sure the card is correctly installed and browser (and app) caches are cleared.

**Comment by spandi** [comment]
I had the very same issue on my Android HAS mobile app. Clearing the cache of the app (App info -> Storage & cache -> Clear cache) did not help. I had to also clear the app storage (App info -> Storage & cache -> Clear storage) which I found a bit strange. Anyway, now after this it works like expected.

**Comment by Serhioromano** [comment]
Try on incognito tab. If it works it is cache problem
