### ISSUE TITLE
Fill transpancy lost when setting fill color

### ISSUE THREAD

**Issue by lnaylor13** [alexarch21/history-explorer-card#189]
Hello, I love the cards, they're great!

One issue I've found is when setting the fill color on a line graph with 2 entities I'm losing the transparency. Letting the default colors be applied, both entities can be seen but once the fill color is set the second entity disappears behind the first.

Can we get the transparency to stick around after having the color set? (Notice that the fill also disappears when the color option is set for the entity as well).

HA version - 2023.7.1
HE Card version - 1.0.47

**Comment by alexarch21** [comment]
Post your yaml please.

**Comment by lnaylor13** [comment]
type: custom:history-explorer-card
cardName: historycard-23559642
header: Brightness
defaultTimeRange: 12h
lineMode: curves
decimation: fast
stateTextMode: auto
stateColors:
  sun.below_horizon: '#6b3f00'
  sun.above_horizon: '#ff9800'
graphs:
  - type: timeline
    entities:
      - entity: sun.sun
  - type: line
    options:
      ymax: 1200
      rounding: 1
    entities:
      - entity: sensor.front_door_sensor_illuminance
        name: Front Door
        color: '#ff9800'
        fill: '#ffefdc'
      - entity: sensor.backyard_sensor_illuminance
        name: Backyard
        color: '#3498db'
        fill: '#e5effa'
  - type: line
    entities:
      - entity: sensor.dining_room_presence_sensor_light_sensor_light_level_2
        name: Dining Room
      - entity: sensor.dining_room_mi_note_2_light_sensor
        name: Mi Note 2

**Comment by lnaylor13** [comment]
Apologies but I noticed the rgba setting you have listed for some of your fills and realized the last parameter is for transparency ... If I switch to that instead of hex I can maintain the setting.

Updated to ...

    entities:
      - entity: sensor.backyard_sensor_illuminance
        name: Backyard
        color: '#3498db'
        fill: rgba(229,239,250,0.5)
      - entity: sensor.front_door_sensor_illuminance
        name: Front Door
        color: '#ff9800'
        fill: rgba(255,239,220,0.5)

**Comment by alexarch21** [comment]
Yeah there seems to be a small bug regarding alpha values when supplying the colors as hex. I added this to the list of things to look into.

Supplying rgba strings is the workaround, as you found out already.

**Comment by alexarch21** [comment]
Actually it works fine, you just haven't supplied the alpha in your hex colors: `fill: '#ffefdc'` should be `fill: '#ffefdc88'` or similar.

**Comment by lnaylor13** [comment]
Awesome, thanks for that. Didn't realize that you could add transparency in hex.
