### ISSUE TITLE
Change Color from Timeline

### ISSUE THREAD

**Issue by MrThiemann** [alexarch21/history-explorer-card#19]
how are the colors defined here?  

is there a way to adjust the color of the timeline?  

in an example: a thermostat… 

comfort temperature = 21 degrees == green.  
about == orange.  
under == blue

![image](https://user-images.githubusercontent.com/54147030/154404296-71f2ccda-88e9-4334-aace-e2cdf945ffcb.jpeg)

**Comment by alexarch21** [comment]
It's all explained in the readme.
