### ISSUE TITLE
FR: Allow override of max tick density calculation

### ISSUE THREAD

**Issue by dxmnkd316** [alexarch21/history-explorer-card#191]
Hi Alex.  I know you've implemented a tick density with the timeTickDensity option.  I'm finding with some of the grid cards, this can be a bit conservative (see image below, scaled @ 50%).  In case below, I was hoping to get a tick for every day instead of every three.  

I read through some of the other issues/FRs and understand it's a hard balance to strike for various monitors and widths.  So maybe this is a bad idea that could lead to unintended consequences.

What's the likelihood of adding an option to disable the following line in history-explorer-card.js:
`return Math.max(( width < 650 ) ? 4 : ( width < 1100 ) ? 3 : ( width < 1300 ) ? 2 : ( width < 1900 ) ? 1 : 0, densityLimit);`

If not optionally disabling that line, perhaps we could specify a number of ticks instead of trying to play with density.  

<img src="https://user-images.githubusercontent.com/46753733/256291560-eefb951e-c041-4d94-81ff-4a17863fcce3.png" data-canonical-src="https://user-images.githubusercontent.com/46753733/256291560-eefb951e-c041-4d94-81ff-4a17863fcce3.png" width="50%" height="50%" />

Thanks

**Comment by alexarch21** [comment]
Get V1.0.50 and try this:
```
timeTicks:
  densityOverride: higher
  dateFormat: short
```

**Comment by alexarch21** [comment]
I'm closing this due to lack of feedback.
