### ISSUE TITLE
FR: Averaging/Mean Values per Entity

### ISSUE THREAD

**Issue by dafunkydan** [alexarch21/history-explorer-card#192]
Sometimes it is needed to see excacty the Development of a Value, but sometimes that makes it harder to see/interpretate.

I would love to have the Possibility not to have every single Measurement drawn, but to control how many Datapoints (per Hour?) are shown, and have the average/mean Value drawn.
For Example - this Graph shows the Temperatures for Inside/Outside/Conservatory:

![grafik](https://github.com/alexarch21/history-explorer-card/assets/103875104/777e5d4d-6c10-4e17-b0fa-ce6825349928)
I think that makes it way easier to see whats going on and interprete 

This Way, one even could even build e.g. Daily Averages (0,04 Points per Hour).

**Comment by alexarch21** [comment]
That sounds more like something that should be done by an averaging sensor outside of the card, and that averaged value can then be graphed. I feel that these kind of data manipulations are out of scope for a graphing card. Maybe in the future I will make the custom processing part of the card more powerful, allowing things like this be done on the fly by the user.

For your specific case, there is a workaround though. You can use long term statistics as data source. They provide built-in averaging (or min/max):
```
statistics:
  mode: mean
  period: hour
  force: true
```

**Comment by dafunkydan** [comment]
Thanks for your awesome quick Response! 
> an averaging sensor outside of the card

I thought about that as well - but that would both increase Recorder Database, as well as LTS. If different Intervals should be displayed, multiple Times. Because of that i shied away from inventing multiple Sensors

> custom processing part of the card 

While i never really understood that Option, that sounds cool anyway 👍 

> use long term statistics as data source

This is awesome! I wasn't aware of `force: true` .Only Downside might be, that it (obviously) can only be used with Statistics-Entities, and (again obvious) doesn't show the latest Values. But that will probobaly do it, i only have to make sure to have Statistics for all needed Entities.

> out of scope for a graphing card

I can only compare that with `type: custom:mini-graph-card`, which can do kind of averaging via the Option "Points per Hour".
Personally I think that the Way a Graph gets displayed is totally in Scope for a graphing Card :-D 
But don't get me wrong - if you think that is nothing for that Card, i am totally fine with that. And still will stick it :-) And maybe Someday a way to sample Values down via processing arises...

**Comment by dafunkydan** [comment]
```
statistics:
  mode: mean
  period: hour
  force: true
```
Actually, this is pretty neat! Sure, for Entities without LTS that unfortunatly doesn't work. But it is Way more efficient than inventing multiple averaging Sensors 👍 

Would there be an easy Possibility to implement a function, to use acutual _Sensor-Data after the newest LTS Data_? Then everything would be smoothed, and for tha last max 60 minutes it would show what is going on...

**Comment by alexarch21** [comment]
Right now I will leave it as-is. New LTS functions (including the documentation of this hidden feature) will probably come in one of the later releases this year. Possibly the process functions will be improved to allow manual custom low-pass filters too.
