### ISSUE TITLE
Get last value of day

### ISSUE THREAD

**Issue by JanDetrez** [alexarch21/history-explorer-card#198]
First, many thanks for this awesome plugin!

I'm trying to get bar charts for my self-sufficiency for each day.

I currently have a template sensor, which calculates my self-sufficiency in real-time that restarts each day. 
![image](https://github.com/alexarch21/history-explorer-card/assets/16916740/1ca278e8-af45-42f4-a0b3-27fd9412dfa2)

Is it possible to extract/show the last value of the day (ie the self-sufficiency across that day), and plot only that value for each day ?

**Comment by alexarch21** [comment]
Not really. The card doesn't allow access to individual values, that's not really in scope for a graphing card.

That's sounds like something that would be perfect as a template sensor in HA, so it could both be plotted (as a separate entity) and also displayed as a value elsewhere in your UI !
