### ISSUE TITLE
graph view starting from midnight of current day

### ISSUE THREAD

**Issue by JanDetrez** [alexarch21/history-explorer-card#199]
Is this possible?

Coming from Apexcharts, which allows this.
![image](https://github.com/alexarch21/history-explorer-card/assets/16916740/63c0de2f-f147-4e66-a487-08f3cc272978)

**Comment by alexarch21** [comment]
Yes:
```
defaultTimeRange: 1d
defaultTimeOffset: 1D
```

**Comment by alexarch21** [comment]
See my example above.

defaultTimeOffset: 1**D**

Upper case '**D**'. Lower case 'd' denotes a relative time offset.

**Comment by JanDetrez** [comment]
Hah, now it works, thanks!

I tested it exactly like you mentioned in your first post, but nothing happened, then I changed it to lower case "1d", and it behaved as I explained in post 2. Now it works with "1D", great, thanks!

**Comment by JanDetrez** [comment]
Sorry for re-opening, but can something similar be done to have the plot only show Mon-Sun of the current week? 

In analogy of above, this doesn't work
defaultTimeRange: 1w
defaultTimeOffset: 1W

I don't see more information on this in the docs

**Comment by alexarch21** [comment]
No, weeks are not supported. Only days (D) or months (O).
