### ISSUE TITLE
Counter entities show as wrong chart

### ISSUE THREAD

**Issue by maorcc** [alexarch21/history-explorer-card#201]
Home Assistant [Counter entities](https://www.home-assistant.io/integrations/counter/) are numerical sensors, but on history-explorer-card they are shown as non-numerical sensors.

Here is an example of a history-explorer-card showing a Counter entity.  See that it is difficult to evaluate the values:
<img src="https://github.com/alexarch21/history-explorer-card/assets/255973/fcb88c54-434b-45ae-9434-fc6a4282eda7" width="600">

Here is the regular Home Assistant History Graph card showing the counter entity as a line graph:
![image](https://github.com/alexarch21/history-explorer-card/assets/255973/db095d55-552e-4cb0-aea1-550314423ea8)

I expect counters to show as a line graph, like any other numerical sensor.

**Comment by alexarch21** [comment]
Line graphs are for continuous, interpolateable functions. Integer counters are neither. Line graphs are only used as default for entities with a valid unit of measure in this card.

If you want your counters to be displayed as line graphs by default, you can override their type using `entityOptions`. See the readme.
