### ISSUE TITLE
Cannot set properties of undefined (setting 'valid')

### ISSUE THREAD

**Issue by ClassicGOD** [alexarch21/history-explorer-card#202]
After updating to 1.0.48 the graph renders correctly but when it refreshes (refresh: automatic: true) it only shows "Cannot set properties of undefined (setting 'valid')" message. reverting to 1.0.47 fixes the issue. 

Home Assistant 2023.9.1, happens on all themes.

**Comment by alexarch21** [comment]
Can you please post your config yaml ?

**Comment by alexarch21** [comment]
Ok found it. Stupid mistake on my side. Hotfix is on the way.

**Comment by alexarch21** [comment]
There you go. V1.0.49 is up. Should fix this. Please test !

**Comment by ClassicGOD** [comment]
Looks like it's fixed! Thanks :)

**Comment by alexarch21** [comment]
Okey dokey then !
