### ISSUE TITLE
timeline chart: tooltip only shows visible times (not real times)

### ISSUE THREAD

**Issue by kusmi** [alexarch21/history-explorer-card#205]
When zooming into a timeline, the tooltip only displays the currently visible times and durations - instead of the real ones. See attached screenshots

**Screenshot 1: When zooming out you see "rural amenities detection" took 6h36m11s:**

<img width="1068" alt="Screenshot 2023-09-15 at 09 53 24" src="https://github.com/alexarch21/history-explorer-card/assets/448222/22836faf-95b4-4465-90b0-3203a873e408">

**Screenshot 2: When zooming in, the tooltip now just displays 2h:**

<img width="1068" alt="Screenshot 2023-09-15 at 09 53 48" src="https://github.com/alexarch21/history-explorer-card/assets/448222/6b1f699d-275f-495f-9c74-396b245db86f">

**Comment by alexarch21** [comment]
That's a limitation of the HA recorder API, which will generate 'fake' state times on partial database requests. There is nothing I can do about this, I'm afraid.

The only workaround is to load a longer timeframe when the card opens, using defaultTimeRange. The durations will then be correctly reported within that time range.

**Comment by alexarch21** [comment]
Well, yes and no. It's complicated 🙂

This is definitely not a bug in the recorder. This was a conscious design decision on their side. I'm not exactly sure about the why, but they probably had good reasons to go that way. Changing this behavior now is going to break lots of things.

Now, the history explorer could handle this situation / limitation a bit better. These virtual states are DB artifacts and could be filtered out. But this is very finicky abd will not have 100% success rate, as it is not always possible to distinguish between virtual states and an actual real state that just happens to be in the wrong spot.

So I took the easy way out and just clamp the state duration to the visible cache boundaries and just do some simple (but safe) double state filtering within the visible area.
