### ISSUE TITLE
Entity name being cut off

### ISSUE THREAD

**Issue by jazzyisj** [alexarch21/history-explorer-card#208]
This is the same issue I have with the core history card.  The entity names are always cut off on the left.  It makes it very difficult to figure out what entity you're looking at if you have many similar ones.

<img width="230" alt="image" src="https://github.com/alexarch21/history-explorer-card/assets/44064559/b703d425-c2e5-4c34-8227-2d23f493e06b">

**Comment by alexarch21** [comment]
Then make the label area wider (`labelAreaWidth`) or override the names with shorter ones (`name`). It's all explained in the readme.

**Comment by jazzyisj** [comment]
I'm so sorry.  I just found it in the readme trying to figure something else out and was coming back to close the issue with an apology for bothering you.

Awesome card.  Better than the core history graph in every possible way.  Thank you!

**Comment by jazzyisj** [comment]
I do have a suggestion though.  It would be great if you organized all the card options into summary tables like many cards do.  Makes it much easier for finding an option syntax quickly.  Thanks again.

[An example.](https://github.com/custom-cards/button-card#main-options)

**Comment by alexarch21** [comment]
No worries, no bother :) Glad you enjoy the card.

I'm fully aware that the readme is getting very long and convoluted and finding a specific bit of info is sometimes hard. A better organization would help a lot. But writing documentation is very time consuming and refactoring it is even worse...
