### ISSUE TITLE
No entity pull-bown menu on HA Android app

### ISSUE THREAD

**Issue by Cook23** [alexarch21/history-explorer-card#209]
I read should be solved since v1.0.17 with HA android app

I have version v1.0.50 and still no pull down menu. Delete HA app and reinstall It changed nothing.

works with chrome app (very nice right left sliding entity selector)

works with fully kiosk (traditional boring pull down) 

don't woks with HA app (nothing to select entity) 

don't works with Firefox app (nothing to select entity but I believe it's officially not supported so it's normal)

**Comment by Cook23** [comment]
no solution ?

**Comment by alexarch21** [comment]
Sadly the history explorer card has been declared end of life and won't be developed anymore. So I will have to close this issue / FR without resolution. This repository will be archived and set to read-only shortly.

See this post on the HA forum for more information: 

https://community.home-assistant.io/t/new-interactive-history-explorer-custom-card/369450/978
