### ISSUE TITLE
FR: Sync zoom or time interval over multiple history explorer elements

### ISSUE THREAD

**Issue by Sebalux** [alexarch21/history-explorer-card#211]
Would love to see an option that the time interval or zoom selection I have chosen on one history explorer entity to be synced to other entities on the same page.. Possible maybe?

Maybe the same could be established for the "scroll position" to sync to another card? Like I have scrolled back in card 1 to 6 hours before, than the second card will jump to the same position too.

Thanks
Sebalux

**Comment by alexarch21** [comment]
Sadly the history explorer card has been declared end of life and won't be developed anymore. So I will have to close this issue / FR without resolution. This repository will be archived and set to read-only shortly.

See this post on the HA forum for more information: 

https://community.home-assistant.io/t/new-interactive-history-explorer-custom-card/369450/978
