### ISSUE TITLE
Feature request: set default line width

### ISSUE THREAD

**Issue by gedger** [alexarch21/history-explorer-card#213]
Would be really good to be able to set the default line width for all line graphs rather than for each item.

Even more important when adding items from the UI where it's not possible to set the line width.

**Comment by alexarch21** [comment]
You can configure line width for dynamically added entities using `entityOptions`. [See here](https://github.com/alexarch21/history-explorer-card#customizing-dynamically-added-graphs).

**Comment by gedger** [comment]
Thanks, I spent ages in the documentation and still missed that! I would still like to be able to set a default line width though, I do find the default to be too wide and I never mix widths on a graph. However, it's a nice have rather than need so I'll close this and leave the idea in the back of your mind....

**Comment by alexarch21** [comment]
In that case, you're welcome to open a feature request for that ! No guarantees on when/if it will make it into a release, but this would be a very simple addition.
