### ISSUE TITLE
FR: add entities of groups

### ISSUE THREAD

**Issue by erkr** [alexarch21/history-explorer-card#216]
Most of my automations and cards use groups to populate. This minimises the maintenance when sensors come and go.
Please allow to add entities that contain the `entities_id` list attribute as a `group` where all entities listed in the  `entities_id` attribute are added.
The syntax could be:
``` 
Entities:
  - group: sensor.my_group
``` 
This would allow me to replace many history cards, where I now use groups to populate (I use the `auto entities` card for injecting the group entities)

**Comment by teskanoo** [comment]
@erkr - I would also much appreciate the ability to expand a group of entities. I have tried and failed to get this card working with auto-entities. If you have achieved this... would you perhaps be able to provide me an example where you expand the entities of a group using auto-entities in conjunction with this card?

**Comment by erkr** [comment]
I can't get history card working in auto entities either

**Comment by alexarch21** [comment]
Sadly the history explorer card has been declared end of life and won't be developed anymore. So I will have to close this issue / FR without resolution. This repository will be archived and set to read-only shortly.

See this post on the HA forum for more information: 

https://community.home-assistant.io/t/new-interactive-history-explorer-custom-card/369450/978
