### ISSUE TITLE
local daylight time affects rendering in subtle ways

### ISSUE THREAD

**Issue by mfiano** [alexarch21/history-explorer-card#218]
Today was daylight savings time for me (EST), boo. My graphs showed two oddities, with the first probably being correct-ish, if we are to render with local times.

1) There are two 1:00am-2:00am intervals today.

2) Panning the graphs experience a hiccup when the end of the first interval/start of the second pans into view from off screen left, which visually comes out as the graph teleporting backwards an hour as you are panning forward.

My gut tells me that something is only looking at relative distance to some time and not how many absolute intervals in world space coordinates we are located in.

**Comment by alexarch21** [comment]
Most likely, there is no specific code to handle DST switches. DB access should be OK (so the data should be correct), but it is very likely that scrolling will experience hickups when an hour basically appears twice (with different data). A missing hour should just generate an empty graph / missing values for that time.

Fixing this correctly is non-trivial. What do you display during the 'lost' hour ? You'd have the explicitly add the TZ change in the graph, and the time axis becomes non-monotonically increasing. I'm not sure if the amount of work to do this is worth it. It's just a display glitch that is going to fix itself once the DST jump goes out of the purge period.

**Comment by alexarch21** [comment]
I won't have the time to look into this, I'm afraid. The ratio between the amount of work this would require to fix and the benefits it would provide is not worth it. If you want 100% continuous data even through DST jumps, then the best way is to export the CSV which does not suffer from this display glitch.
