### ISSUE TITLE
FR: Use localized formats of user profile for data export

### ISSUE THREAD

**Issue by GWL20** [alexarch21/history-explorer-card#219]
At first I would like to thank you for setting up this great card. I am only missing the possibility to set the number format (use a comma instead of the dot as decimal separator) so that decimal numbers are shown correctly when opening the csv-file in Excel. (I am aware of the workarounds). A new parameter under the "csv:" setting would do, however the use of the user profile information would be even nicer.

Thanks
GWL20

**Comment by alexarch21** [comment]
I can see this being useful. A new parameter in the csv section of the YAML would be the way to go for this. I would avoid tying it to the user profile, as this makes it less flexible (people may not want to export in the same locale format).

**Comment by alexarch21** [comment]
Added to V1.0.51.

[See here](https://community.home-assistant.io/t/new-interactive-history-explorer-custom-card/369450/940).
