### ISSUE TITLE
Display text in line with device class

### ISSUE THREAD

**Issue by RogerSelwyn** [alexarch21/history-explorer-card#22]
When using the inbuilt HA History panel it shows text on the bars that are appropriate for the device class. So a binary sensor that is a motion sensor shows 'clear' or 'detected' instead of off/on. Is it possible to match this capability?

**Comment by alexarch21** [comment]
This is now available in V1.0.29. 
See readme under [Timeline charts](https://github.com/alexarch21/history-explorer-card#timeline-charts).

**Comment by RogerSelwyn** [comment]
Great stuff, thanks!
