### ISSUE TITLE
Feature Request: combine bar graph from multiple sources vertically, not horizontally

### ISSUE THREAD

**Issue by bisbastuner** [alexarch21/history-explorer-card#223]
If you add more than one source to a bar graph, they always combine in a way that, for each period of time, space is dedicated to every source, and bars are grouped horizontally one next to the other.
This FR proposes an option to group bars vertically, so that for each period the data from each source is piled vertically to a single bar. Every piece of the bar would be colored with the source color.
If one source has no data, or its data is 0, the source will simply not be shown.
This is similar to what the Home Assistant Energy card does when displaying energy sources consumption.

**Comment by alexarch21** [comment]
Added to V1.0.51.

[See here.](https://community.home-assistant.io/t/new-interactive-history-explorer-custom-card/369450/940)
