### ISSUE TITLE
Feature request: Vertical reference line

### ISSUE THREAD

**Issue by GreeMart** [alexarch21/history-explorer-card#224]
As i said in "Buy me a coffee" section: Awesome project! Thanks so much

I think would be useful having a vertical line appearing across all the graphs when you hover your mouse pointer over a graph. Picture as example:
![history-explorer-feature](https://github.com/alexarch21/history-explorer-card/assets/87694231/eaf4c34a-ff96-4434-bc5d-a709e1f3dfa7)

**Comment by alexarch21** [comment]
Would make sense I guess (as an option).

**Comment by alexarch21** [comment]
Added to V1.0.51.

[See here](https://community.home-assistant.io/t/new-interactive-history-explorer-custom-card/369450/940) on how to use it.
