### ISSUE TITLE
Feature Request: Add weekly option for bar graph 

### ISSUE THREAD

**Issue by gedger** [alexarch21/history-explorer-card#225]
Homes / people / data often follows a weekly pattern and it would be really useful to be able to group the data by week in addition to the 10min/hourly/daily/monthly/as_line provided.

**Comment by alexarch21** [comment]
Sadly the history explorer card has been declared end of life and won't be developed anymore. So I will have to close this issue / FR without resolution. This repository will be archived and set to read-only shortly.

See this post on the HA forum for more information: 

https://community.home-assistant.io/t/new-interactive-history-explorer-custom-card/369450/978
