### ISSUE TITLE
defaultTimeRange doesn't work for non-predefined ranges

### ISSUE THREAD

**Issue by rob-vandenberg** [alexarch21/history-explorer-card#226]
I am trying to set **defaultTimeRange** to 25 hours, but it doesn't work. It shows me 4 days instead.
24 hours works, so does 12. But 25 doesn't work, and neither do 23 or 13.
As far as I can tell it only seems to work for hours up to 12 and then for multiples of 12.

History explorer card version 1.0.50

HA Core version 2023.11.3
HA Supervisor 2023.11.3
HA OS 11.1
Frontend 20231030.2

**Comment by alexarch21** [comment]
That's by design. If a non-predefined range is requested, the card will snap to the next higher one.
