### ISSUE TITLE
Option to include fix horizontal lines (used for thresholds)

### ISSUE THREAD

**Issue by fredck** [alexarch21/history-explorer-card#227]
In charts, both line and bar types, it is a common requirement to preset thresholds as fixed lines. This is not possible to easily achieve currently.

Right now, the only way is to created a (pointless) entity with a fixed value and add it to the graph, just like I did here:
<img width="868" alt="image" src="https://github.com/alexarch21/history-explorer-card/assets/630060/eb35aa6a-d518-4ecb-bbc9-9c2e135d7dfa">

The thing is that this entity doesn't have enough history to fill the chart. We can clearly see the moment I've created it. So there is no way to make it work for before that date.

Also, this is more like a hack than a proper way to achieve that.

It would be nice to have such feature. It could be a new "lines" or "fixed_lines" or "thresholds" configuration inside a graph, where one could give a name to the line, a value and many of the option we already have for entities.

**Comment by alexarch21** [comment]
Use a process function to force a constant value. No need for a dummy sensor or any additional recorder entries.

**Comment by alexarch21** [comment]
It doesn't work without entity, but it's just a placeholder. Use any entity you already have on the graph, doesn't matter, it just has to be a valid one. Use a process function to force it to a constant value state.

**Comment by alexarch21** [comment]
It's a workaround that does exactly what you need and with minimal side effects (if any).

Yes it would be nice to have dedicated support for this feature. It would also take time to implement. I'm gladly accepting a PR for this 🙂

**Comment by alexarch21** [comment]
Sadly the history explorer card has been declared end of life and won't be developed anymore. So I will have to close this issue / FR without resolution. This repository will be archived and set to read-only shortly.

See this post on the HA forum for more information: 

https://community.home-assistant.io/t/new-interactive-history-explorer-custom-card/369450/978
