### ISSUE TITLE
What's the bottleneck to speed?

### ISSUE THREAD

**Issue by bastiaanterhorst** [alexarch21/history-explorer-card#228]
Thanks for this card, it is incredibly useful!

One thing I am wondering about is how I can make it faster. I notice that switching to a different time scale or panning back can take a long time to load; between 5 and 30 seconds.

Looking at my HA instance CPU it doesn't come above 10%. Memory is also low.
My data is hosted on an external MariaDB instance (on my NAS), and that also has CPU usage <10%, low memory, and low disk utilisation.

So I'm wondering what the bottleneck is. If anyone has a clue, I'd really appreciate any hints about how to improve the speed I see.

Thanks!

**Comment by alexarch21** [comment]
Your DB access is the bottleneck here. With a high speed DB (even on the default SQlite backend), the operations you listed are pretty much instant.

**Comment by bastiaanterhorst** [comment]
Thanks, your nudge led me to install MariaDB via docker which led to a huge speed increase. Thanks!
