### ISSUE TITLE
Labels should display "processed" value

### ISSUE THREAD

**Issue by fredck** [alexarch21/history-explorer-card#229]
The combination of `showCurrentValues: true` and `process` is now a bit confusing since the labels don't show the "processed" value but the raw state value of the entity.

For example in the following graph, I use a simple `process: '-state'`  configuration for each of the entities (except one) so they show positive in the charts. The labels though still show the negative value.

<img width="868" alt="image" src="https://github.com/alexarch21/history-explorer-card/assets/630060/eb35aa6a-d518-4ecb-bbc9-9c2e135d7dfa">

That's a simple case but more complex ones (like the workaround proposed in #227) have an even more evident negative impact.

**Comment by alexarch21** [comment]
Correct, that's a bug. It should show the processed value. The `scale` option is most likely affected too.

**Comment by alexarch21** [comment]
Thinking about this a little more, it should probably be an option. I can think of scenarios where you would want to show the original state instead. Think of a upload/download type graph, where one could use a scale of -1 to flip one of the entities for visual purposes, but where one would want to keep the original states in the label.

**Comment by alexarch21** [comment]
That would be a breaking change, which is a total no-go for this card.

The only way to implement this correctly is through an option.

Reclassified as a FR.

**Comment by fredck** [comment]
For the current state of things, I see this as a bug. In the end user pov, it's weird that the current value doesn't match what I see in the graph. Additionally, much probably you didn't implement this in that way on purpose.

Major releases are there for such kinds of changes ;)

**Comment by alexarch21** [comment]
Sadly the history explorer card has been declared end of life and won't be developed anymore. So I will have to close this issue / FR without resolution. This repository will be archived and set to read-only shortly.

See this post on the HA forum for more information: 

https://community.home-assistant.io/t/new-interactive-history-explorer-custom-card/369450/978
