### ISSUE TITLE
Catalan translation

### ISSUE THREAD

**Issue by PutoPunko** [alexarch21/history-explorer-card#231]
{
    "ui" : {
        "label" : {
            "type_to_search" : "Escriu per buscar una entitat a afegir",
            "error_retreiving" : "No s'han pogut recuperar les entitats disponibles!",
            "loading" : "Carregant entitats disponibles...",
        }, 
        "popup" : {
            "remove_all" : "Eliminar tots els gràfis afegits dinàmicament?",
            "enable_panel" : "Activar panell info historia?",
            "disable_panel" : "Desactivar panell info historia ?"
        },
        "menu" : {  
            "export_csv" : "Exportar com a CSV",
            "export_stats" : "Exportar estadístiques com a CSV",
            "remove_all" : "Eliminar tots els gràfics afegits",
            "enable_panel" : "Activar panell info historia",
            "disable_panel" : "Desactivar panell info historia"
        },
        "ranges" : {
            "l_hour" : "< 1 H",
            "hour" : "1 H",
            "n_hours" : "%1 H",
            "day" : "1 Dia",
            "n_days" : "%1 Dies",
            "week" : "1 Setmana",
            "n_weeks" : "%1 Setmanes",
            "month" : "1 Mes",
            "n_months" : "%1 Mesos",
            "year" : "1 Any"
        },
        "interval" : {
            "_10m" : "10 min",
            "hourly" : "Horari",
            "daily" : "Diari",
            "monthly" : "Mensual",
            "rawline" : "Línia"
        }
    }
}

**Comment by alexarch21** [comment]
Sadly the history explorer card has been declared end of life and won't be developed anymore. So I will have to close this issue / FR without resolution. This repository will be archived and set to read-only shortly.

See this post on the HA forum for more information: 

https://community.home-assistant.io/t/new-interactive-history-explorer-custom-card/369450/978
