### ISSUE TITLE
Support of multiple Y-axes

### ISSUE THREAD

**Issue by wrfz** [alexarch21/history-explorer-card#233]
Sometimes it is useful and necessary to display several line graphs in one diagram.
Currently there is already a way to do this. It is a great functionality.
As long as the value ranges of the characteristic curves are in a similar range, it is usable.
However, if you want to display characteristic curves with very different value ranges,
then the characteristic curve with a significantly smaller value range may be pushed close to 0.
In a specific case, I have the temperature of the hot water and the power consumption of a heat pump:

![grafik](https://github.com/alexarch21/history-explorer-card/assets/77174685/a8426a66-b4f0-4ef4-b445-8730c448d217)

If I put both curves together, I get the following picture:
![grafik](https://github.com/alexarch21/history-explorer-card/assets/77174685/b5930333-f085-4a31-8425-a0316328584d)

I would like to see how the power peaks are related to the change in water temperature.
Unfortunately, the graph cannot be used for such evaluations.
The power consumption curve is too compressed.

The problem could be solved if History explorer card supported several Y-axes with their own value ranges.
It would also be nice if you could specify for each axis whether it should be displayed on the left or right.
Similar to what is done here:

https://www.advsofteng.com/doc/cdnetdoc/multiaxes.htm

Thanks a lot!

**Comment by alexarch21** [comment]
This isn't something planned at this moment, due to lack of free time on my side. Maybe in the future or if someone else submits a PR.

**Comment by alexarch21** [comment]
Sadly the history explorer card has been declared end of life and won't be developed anymore. So I will have to close this issue / FR without resolution. This repository will be archived and set to read-only shortly.

See this post on the HA forum for more information: 

https://community.home-assistant.io/t/new-interactive-history-explorer-custom-card/369450/978
