### ISSUE TITLE
Adding entities by their friendly names instead of UID ?

### ISSUE THREAD

**Issue by eigenbaunerd** [alexarch21/history-explorer-card#234]
It can be quite cumbersome to select from the long list of entities in the pull-down menu, especially if they show up with UID only instead of friendly names (which is the case in the standard statstics cards). In my case, the UIDs for many sensors by the same manufacturer are almost similar and very long.
Is there a way to change the name that the entities are showing up with in the pull-down-menu?

**Comment by alexarch21** [comment]
Sounds like a good idea for a feature request !

**Comment by alexarch21** [comment]
Sadly the history explorer card has been declared end of life and won't be developed anymore. So I will have to close this issue / FR without resolution. This repository will be archived and set to read-only shortly.

See this post on the HA forum for more information: 

https://community.home-assistant.io/t/new-interactive-history-explorer-custom-card/369450/978
