### ISSUE TITLE
Fix start / end date

### ISSUE THREAD

**Issue by KlausV66** [alexarch21/history-explorer-card#235]
Hi,
really nice tool. 
I would like to know if possible to define a fix start / end date like 8am - 5pm.
It would help for my solar graph to show only the values between sunrise and sunset. 
Thanks so much.
Klaus

**Comment by alexarch21** [comment]
Not precise time ranges like this. The best you can do is show the entire current day (fixed):
```
defaultTimeRange: 1d
defaultTimeOffset: 1D
```

**Comment by KlausV66** [comment]
OK, thanks. Maybe, in a next release you can include such function.

**Comment by alexarch21** [comment]
Sadly the history explorer card has been declared end of life and won't be developed anymore. So I will have to close this issue / FR without resolution. This repository will be archived and set to read-only shortly.

See this post on the HA forum for more information: 

https://community.home-assistant.io/t/new-interactive-history-explorer-custom-card/369450/978
