### ISSUE TITLE
Export csv fil like 5 min ?????

### ISSUE THREAD

**Issue by Hot-Rod6811** [alexarch21/history-explorer-card#236]
Hello
I just have one question 
First, I want to thank you for the best card for Home Assistant. (export to csv file is the best for me) 
I've been using this for a year now. 
Now to the question!! 
I have a weather station that I export out temp as csv file. I want/can I get data type every  5 minutes. 
Why???? 
Export csv file (gives for me) = data between 30 sec - 1 min too much data for me. 
Export statstik csv file = data 1 hr too little data for me.

Change here would be great ??????

type: custom:history-explorer-card
csv:
  separator: ';'            # Use a semicolon as a separator, the default is a comma
  timeFormat: 'DD/MM/YYYY'  # Customize the date/time format used in the CSV. The default is 'YYYY-MM-DD HH:mm:ss'.
  statisticsPeriod: hour    # Period used for statistics export. Hour, day or month is supported. Default is hour.
  exportAttributes: true    # Export all entity attributes along with their state, in separate columns. Default if off (no attrbutes).
  numberLocale: 'en-US'     # Format numbers using the given locale. If this settings is not defined, the raw DB values will be written (no formatting).

Sometimes 5 minutes.  (out temp)
Default  hour 

My English is not good (Used Google Translate)

Thank you for all the work/hours you put into this card

Hot-Rod6811

**Comment by alexarch21** [comment]
```
csv:
  statisticsPeriod: 5minute
```

In the future please use the HA forums for support and to ask questions about how to use the card. Github issues are reserved for bug reports and feature requests. Thanks !
