### ISSUE TITLE
Bar chart: place x-axis label below the bar

### ISSUE THREAD

**Issue by Kanecaine** [alexarch21/history-explorer-card#237]
Hello and a happy new year!

In my opinion it would make very much sense to place the x-axis labels centered below the bar chart, as it does the statistic graph card (here on the left):

<img width="1178" alt="Bildschirmfoto 2024-01-01 um 18 13 20" src="https://github.com/alexarch21/history-explorer-card/assets/99053167/18b8e471-4aa1-4e4d-906f-0ff020786e76">

Would that be possible? When there is enough space, as in the picture above, there would be also no need to abbreviate the month names. That would be great.

**Comment by alexarch21** [comment]
Sadly the history explorer card has been declared end of life and won't be developed anymore. So I will have to close this issue / FR without resolution. This repository will be archived and set to read-only shortly.

See this post on the HA forum for more information: 

https://community.home-assistant.io/t/new-interactive-history-explorer-custom-card/369450/978
