### ISSUE TITLE
Bar-chart: show chart value on the graph

### ISSUE THREAD

**Issue by Kanecaine** [alexarch21/history-explorer-card#238]
Hello, would it be possible to show the value right on the graph when displaying a bar chart?

<img width="397" alt="Bildschirmfoto 2024-01-01 um 18 27 49" src="https://github.com/alexarch21/history-explorer-card/assets/99053167/798604fb-9be6-4cc9-8489-33e560436597">

In that case there would be no need for the y-axis and it would be great to have an option to hide it.

**Comment by alexarch21** [comment]
Sadly the history explorer card has been declared end of life and won't be developed anymore. So I will have to close this issue / FR without resolution. This repository will be archived and set to read-only shortly.

See this post on the HA forum for more information: 

https://community.home-assistant.io/t/new-interactive-history-explorer-custom-card/369450/978
