### ISSUE TITLE
Hide interactive inputs

### ISSUE THREAD

**Issue by bigboban** [alexarch21/history-explorer-card#239]
This is great UI component. But i need it on wall dashboard without any interaction. So i need to hide all interactive UI inputs - lens, combo.. I think it is not possible. Is any chance to add some "master" parameter to make graph "read only"?

**Comment by alexarch21** [comment]
Yes it is possible to hide all UI. [Please read the readme](https://github.com/alexarch21/history-explorer-card#changing-the-ui-layout) before opening an issue. Thank you.
