### ISSUE TITLE
HA App crashes with long name templates because history-explorer-cards

### ISSUE THREAD

**Issue by ajavibp** [alexarch21/history-explorer-card#241]
The Home Assistant app was crashing right after opening on some devices. I found that the problem went away if I deleted the history-explorer-cards, so I've been testing until I found the problem. I couldn't see logs because I don't understand, so it was a trial and error search.

The problem is caused by templates with long names. In my case I had one with 65 characters. The funny thing is that it worked perfectly on the PC, as well as on some mobiles, but it blocked the application on others. Reducing the number of characters in the name solved the problem.

Name of the template that was causing me problems: "sensor.thermo_lavadora_congelador_frigochico_frigo_cocina_vitro_pc".

Mobile where it crashed: Doogee N10, Redmi Note 9S with MIUI 13.0.2, Poco X5 5G with MIUI 14.0.6
Mobile where it worked fine: Redmi Note 8 Pro MIUI 12.5.7

Latest stable versions of Home Assistant (Docker) and history-explorer-card (HACS) existing at the time of writing this issue.

**Comment by alexarch21** [comment]
Sadly the history explorer card has been declared end of life and won't be developed anymore. So I will have to close this issue / FR without resolution. This repository will be archived and set to read-only shortly.

See this post on the HA forum for more information: 

https://community.home-assistant.io/t/new-interactive-history-explorer-custom-card/369450/978
