### ISSUE TITLE
Hide space of selector when it is hide

### ISSUE THREAD

**Issue by Bellavista** [alexarch21/history-explorer-card#25]
Hi alexarch21
when i hide the selector there is some lost space in a card
is it possible to recover this space, lengthening the graph
Thank You
![image](https://user-images.githubusercontent.com/46230198/159177764-3f4b9872-4665-471b-98ea-6a6d1f4311f2.png)

**Comment by alexarch21** [comment]
Some unused spacing at the bottom was removed in v1.0.19.
