### ISSUE TITLE
Request....Filter!

### ISSUE THREAD

**Issue by Bellavista** [alexarch21/history-explorer-card#27]
It's a welcome thing to have the ability to filter out the signals.
If I want to see the effect of a filter, such as lowpass, outlier, range, throttle, time_throttle and time_simple_moving_average I have to create a separate sensor and wait to see the effect or process the history data.
It is possible to add this functionality like "decimation"  or a separate signal for comparison.
Thanks you are doing a great job

**Comment by alexarch21** [comment]
I'm afraid that such a feature would be way out of scope for this card.
