### ISSUE TITLE
Request: identify unavailability by gaps in data

### ISSUE THREAD

**Issue by roger-** [alexarch21/history-explorer-card#32]
I have sensors that can't report availability, so when one is down there's simply a gap in the data. Issue is this gap gets interpolated.

Would be nice to be able to specify a max period after which the sensor is assumed unavailable.

**Comment by alexarch21** [comment]
If a gap appears in the graph, then it means that the sensor actually had the `unavailable` or `unknown` state. The card can optionally interpolate over these gaps, that's controlled by the `showUnavailable` setting.

If your sensor never reports these states and there's no actual gap om the graph, just a long time without an updated value, then there's nothing the card can or should do about this. If you'd like your sensor to report unavailable after a while without updates (and it probably should !), then this should be done from within HA itself. Template sensor, expiry delays, etc, depending on the type of sensor it is.

If you just want to avoid the data being interpolated along a curve or similar, you can set the graph to stepped mode instead.
