### ISSUE TITLE
x-Axis scale

### ISSUE THREAD

**Issue by emufan** [alexarch21/history-explorer-card#33]
If you have a wide monitor, the scale/number of descriptions is too high (and/or too hard to read/dustinguish) in some zoom levels, here 1, 2, 6, 12, Or perhaps only if the card is shown in maximal width.

![image](https://user-images.githubusercontent.com/22775515/162917241-3a8a082d-4579-4672-a6a7-3a171ef5e823.png)

![image](https://user-images.githubusercontent.com/22775515/162917274-3201975f-928b-471e-99de-1e77c8a32030.png)

![image](https://user-images.githubusercontent.com/22775515/162917315-e64eb18d-4b36-47fa-9800-8774adad3c6b.png)

![image](https://user-images.githubusercontent.com/22775515/162917345-b7c7b476-26e3-4434-8fbd-d8fef864c154.png)

![image](https://user-images.githubusercontent.com/22775515/162917414-709519e4-095f-4d17-a5ae-046af5170dad.png)

![image](https://user-images.githubusercontent.com/22775515/162917451-2bd68015-1cd8-4846-917d-59cab6a095d2.png)

![image](https://user-images.githubusercontent.com/22775515/162917513-918bc05e-2571-4a38-afe0-efb2a07d37f0.png)

If I have the window a little bit smaler, it is ok.

![image](https://user-images.githubusercontent.com/22775515/162917749-b84a8479-f6fb-4842-ba94-93642247ca1a.png)

Is it possible to improve it?

**Comment by alexarch21** [comment]
There's always possibilities to improve things ;)

Finding a good time tick distribution for all screen widths is tricky, considering there are additional limitations due to the horizontal scrolling or you'll get jumping ticks while you move through the graphs. Can't promise an eta, but I'll look into it.

**Comment by emufan** [comment]
But I think, this is not really screen width related. Because it is happening always, when the cards are displayed in full default HA width. At least here. But of course, not critical. But I wonder if this was the case from the beginning or came with one of the great iterations.

**Comment by alexarch21** [comment]
Can you check if V1.0.22 solves this problem ? You can manually reduce the tick density using:

`timeTickDensity: medium`

Supported modes are `high` (the default), `medium` or `low`.
