### ISSUE TITLE
Range selector vs Zoom level

### ISSUE THREAD

**Issue by Mariusthvdb** [alexarch21/history-explorer-card#34]
<img width="202" alt="Schermafbeelding 2022-04-15 om 14 57 46" src="https://user-images.githubusercontent.com/33354141/163573889-ddc06102-cde9-41af-b414-bc5f66fe39d5.png">

not a strict 'issue' as such I think, but since we have no 'discussion' tab, please allow here.

I must confess I keep being surprised by the way the + and - behave on the top right tool. I would expect a + to widen the range, and vv. 

Don't have to describe it any better than that I think.

ofc, it shows the Lense/magnifier, and is probably a zoom level, like on the Maps. In this context however, I would rather use a range specifier myself, so that might explain the mindbend I experience when ever I click it ;-)

Anyways, maybe you could consider it. 
thanks!

**Comment by alexarch21** [comment]
Yeah I mean it's just a convention, i had to pick one. It's indeed designed like maps, which for me feels natural. But I can see how this can be awkward if you 'just work' the other way round. I can add a toggle in the next release, not a big deal.

**Comment by alexarch21** [comment]
So uhm, for people whos brains work the ~~wrong~~ other way round for zoom-related UI content ;) How would you see that working exactly in the toolbar ? Just swap the behavior of the existing buttons (`-` would zoom in and `+` zoom out) but keep the icons in the same order in the UI ? Or swap them around in the UI too, so have the `+` left and the `-` at the right ?

**Comment by Mariusthvdb** [comment]
uhm too....
I guess, the position of the buttons wouldn't really matter?

+ means more (history in this case), so zoom out. and vice versa

Maybe give the icon placeholder a function? right now, there's the magnifier. If that is selected, it would behave as on Maps. + meaning zooming in (more detail) - zooming out (less detail). but, click the icon, and have Magnifier change to eg mdi:calendar-search, make not behave like:
+ meaning more range, - meaning less range ?

clicking the magnifier icon now does nothing (as far as I can see) other than darken it?

**Comment by alexarch21** [comment]
I don't think I will put in additional logic in the toolbar for this, that would be overengineering it. Just a YAML toggle that swaps the `+` and the `-` behavior. The question is, should this also swap the position of the two icons on the toolbar.

> clicking the magnifier icon now does nothing (as far as I can see) other than darken it?

The magnifier icon activates interactive zoom mode. Click it (it becomes dark, means active) then select and drag a range in one of your graphs with your mouse and it will zoom into the selected range.

**Comment by Mariusthvdb** [comment]
sorry, I missed that interactive zoom mode functionality.

about the positioning, I wouldn't have any definitive suggestions there I am afraid, what would be your reasoning? 
(I guess the beauty of my suggestions would be that there would be no other change in the frontend than the icon change and its related functionality. Holding on to that, I would suggest not changing the position?)

**Comment by Mariusthvdb** [comment]
sure, optional. A yaml toggle, as suggested by https://github.com/alexarch21/history-explorer-card/issues/34#issuecomment-1108444012

**Comment by alexarch21** [comment]
Added a toggle to V1.0.22:

```
uiLayout:
  invertZoom: true
```
`false` is default behavior. `true` inverts it, `+` will now zoom out, `-` will zoom in.

**Comment by denilsonsa** [comment]
Hmm… I think I understand the confusion. Look at these mock-ups:

    [-] [🔍] [+] [ 1 day ⏷]
    
    [🔍] [-] [ 1 day ⏷] [+]

The first one has the +/- buttons around the zoom icon, so it looks like they control the zooming.

The second one has the +/- buttons around the dropdown box, so it looks like they control the dropdown (i.e. the duration).

So, as a suggestion, reordering the buttons could make it more intuitive. (And, yes, I realize I'm commenting on a closed issue.)
