### ISSUE TITLE
Card build and dependencies

### ISSUE THREAD

**Issue by nobodyguy** [alexarch21/history-explorer-card#36]
Hello, thank you for this wonderful HA card.
Would it be possible to also include build scripts/configs and dependencies?
Thanks a lot.

**Comment by nobodyguy** [comment]
I'd love to add a support for long term stats, but I can't without a way to build it.

**Comment by alexarch21** [comment]
There's nothing to build. Just cat the source files together, put the dependencies into a folder (adjust the import directives if needed) and that's it.

Dependencies are in the imports and should be easy to find searching github. The timeline one was modified quite a bit, so I'll upload it into this repo when I get a chance, but the card should also work with the original one.
