### ISSUE TITLE
how to set 24h time?

### ISSUE THREAD

**Issue by wormiedk** [alexarch21/history-explorer-card#37]
My time format is set to 24h in settings which is respected in most of home assistant but the history-explorer-card still shows time in am/pm format.

If I change language from english to english (gb) time format changes to 24h

**Comment by alexarch21** [comment]
Oh yeah I forgot you could change the data format manually. Right now the card uses the locale (the language). I'll add support for manual time format on the next version.

**Comment by wormiedk** [comment]
great :)

**Comment by alexarch21** [comment]
Fixed in V1.0.22.
