### ISSUE TITLE
FR: offset for arrow line

### ISSUE THREAD

**Issue by wormiedk** [alexarch21/history-explorer-card#38]
I use the arrow line to display wind direction however for some reason the arrow line point to the wind source (against the wind direction) while custom:compass-card has the arrow pointing along the wind.

The custom:compass-card has a possibility to offset the wind direction with a number of degrees to display it differently. Maybe that would be a possibility for history explorer card as well?

**Comment by alexarch21** [comment]
> I use the arrow line to display wind direction however for some reason the arrow line point to the wind source (against the wind direction) 
That's weird, it shouldn't. What does your wind direction sensor report as an angle ? It should report the wind origin direction (for example, 180° if the wind comes from the south). The arrows should then show the flow of direction (in the example, they would be pointing upwards to the north). That's the standard way to represent wind direction.

**Comment by wormiedk** [comment]
It seems to have an offset. In this picture the value is 245 but is displayed as more like 65?![image](https://user-images.githubusercontent.com/4417857/165224046-b7063ba7-16e0-42aa-bc9a-ffd737d173a7.jpeg)

**Comment by wormiedk** [comment]
In the app from Netatmo it says 
![image](https://user-images.githubusercontent.com/4417857/165224265-20ee0f38-b13b-4fe9-8215-db8f1b1fad20.jpeg)
