### ISSUE TITLE
Not an issue but a feature question

### ISSUE THREAD

**Issue by stalakerob** [alexarch21/history-explorer-card#39]
Hi, I did not find a way to display the current value of an entity on the graph. Is this possible or is it planned to be supported?
It would be nice to have that since otherwise you have to click/touch a line at the very right of the display which is difficult on a mobile device.

**Comment by alexarch21** [comment]
This isn't possible at this time and is not planned I'm afraid, as displaying realtime entity states would be out of scope for this card.
