### ISSUE TITLE
Feature suggestion: Tooltip duration.

### ISSUE THREAD

**Issue by fennesz** [alexarch21/history-explorer-card#41]
Amazing card! I am extremely happy with it.

Feature suggestion would be to add a duration to the state on tooltip when hovering:

![image](https://user-images.githubusercontent.com/10251312/172807202-381bdd89-ac56-4b4a-b86b-5a587da75248.png)

So it already tells it has been on from 8:31 to 10:54. It would be nice to get the duration of this time in tooltip also (2 hours, 23 minutes).

**Comment by alexarch21** [comment]
Sounds like a great idea for an addition ! Would be an optional toggle then.

**Comment by alexarch21** [comment]
Available in V1.0.23 now.

Add to the config YAML:
`tooltipShowDuration: true`

Default is false (duration is hidden).
