### ISSUE TITLE
HASS Companion cannot load the card

### ISSUE THREAD

**Issue by bwims** [alexarch21/history-explorer-card#43]
Hello,

The Android companion app does not seem to like the custom card.  See screenshot at end.

I'm running the latest version of companion 2022.6.0
Version of card is 1.022

Thanks for your hard work!

![image](https://user-images.githubusercontent.com/18516073/173351091-2ce03f69-bb30-4a40-889c-cbfc236aae16.png)

**Comment by alexarch21** [comment]
I cannot reproduce this. Home assistant 2022.6.5, companion app 2022.6.0. The history explorer card works as expected here.

**Comment by bwims** [comment]
Aha!

I am running 2022.4.6 on the server.  Could that be the problem?  Something
to try at least.

Thanks!

B.

**Comment by alexarch21** [comment]
Unlikely that this would be a problem. It sounds more like a cache issue. How did you install the card, manually or through HACS ? You can always try to restart HA.

What Android version are you on ?
