### ISSUE TITLE
Enhancement Request - Ability to set Chart Height

### ISSUE THREAD

**Issue by GazTheGeek** [alexarch21/history-explorer-card#45]
Fantastic card. Thanks so much to the developer for creating it. It would be helpful to be able to set the chart height. In my use case I just have a single chart and it would be great if I could increase its height to use more of the screen.

Thanks for considering.

<img width="1720" alt="Screen Shot 2022-06-30 at 6 26 20 pm" src="https://user-images.githubusercontent.com/72774034/176630143-b092dba0-6e3e-4193-ac0c-48b936e9b148.png">

**Comment by alexarch21** [comment]
Weird, I could have sworn that this was already available in the card. Looks like I had added the config framework for this to the card, but never added it to the YAML parser. It's only a single line of code to add, so it's going to be in the next version. Only for line graphs though, timeline graphs are difficult to customize.

**Comment by alexarch21** [comment]
Available in V1.0.23 now.

Add to the config YAML:
`lineGraphHeight: 100`

Default value is 250.

**Comment by GazTheGeek** [comment]
Perfect. Thanks. Works great.

**Comment by joenye** [comment]
@alexarch21 Would it be possible to allow us to set `lineGraphHeight` for individual charts? For dashboards with many charts, some charts have a lot of data and need more height, whereas others do not.
