### ISSUE TITLE
Feature Suggestion: Filter for entity drop down

### ISSUE THREAD

**Issue by sarahmva** [alexarch21/history-explorer-card#46]
Just a feature suggestion: I would like to be able to pre-filter the entity drop down so I can limit the available choices and make selection easier. Filter should be partial.

e.g. 
filterDropDown: 'sensor.power_*'

This example setting would only display entities that start with "sensor_power".

**Comment by rforgo** [comment]
I agree with the development proposal

**Comment by alexarch21** [comment]
The feature was added in V1.0.24.

Examples:
```
filterEntities: ''binary_sensor.*"
filterEntities: ''*door*"
```
