### ISSUE TITLE
Feature request: Allow selecting multiple entities in the dropdown menu before clicking away to finalize

### ISSUE THREAD

**Issue by vaibhav2912** [alexarch21/history-explorer-card#49]
Hello,

This is a very helpful card. I was searching for a history card replacement since the core update 2022.7.
Thanks to another user's [post](https://community.home-assistant.io/t/request-common-or-aligned-time-axis-on-all-history-graphs/246613/4?u=vpalande), I found this.

I love the customization options and ease of use.
I was browsing through community post and read in [one of the posts](https://community.home-assistant.io/t/new-interactive-history-explorer-custom-card/369450/124?u=vpalande) that you are working on the feature to allow drag and drop to change the order of entities.

Another feature I think that will increase the ease of use is if you can allow selecting multiple entities from the dropdown list at once.
So user will search for the entity they want and then select one or more entities from the filtered list, then click outside the dropdown list to finalize the selection.

Regards,
Vaibhav

**Comment by alexarch21** [comment]
I can definitely see how this would be useful, but there may be technical limitations with this. I will investigate.

You can also use the new wildcard selection feature if you want to add several sensors in one go, according to some criteria.

**Comment by alexarch21** [comment]
Due to technical limitations it would be a huge amount of work to add this. So I'm afraid this will not happen, unless someone sends in a PR. 

Using wildcards in the entry field can be a workaround for now.
