### ISSUE TITLE
Request: ability to disable interactive features

### ISSUE THREAD

**Issue by JPinSPACE** [alexarch21/history-explorer-card#5]
I realize that the interactive features of history explorer card are one of the main draws, but I find myself accidentally scrolling or changing days when using the phone app interface.

While I'd love to keep the interactive features on a more detailed page with computer use in mind, for my "essentials" page I'd prefer to just specify a time range and lock that into place.

**Comment by alexarch21** [comment]
The tool UI elements can be removed entirely using the uiLayout setting in the YAML, with all options set to hide.
