### ISSUE TITLE
Spacing issues in mobile (iOS app)

### ISSUE THREAD

**Issue by antonio1475** [alexarch21/history-explorer-card#55]
Hi,

On mobile (iPhone 13, HA app), the toolbar "mounts" in 2 rows, also causing the x-axis to fall outside the card.
I think the date and period selectors can be made narrower, since they seem to have a lot of blank space in them (on mobile, not so much in desktop).

Also, the left and right margins are too big, making the graph smaller narrower than it could.

I marked all the spaces that I think could be narrower:

![image](https://user-images.githubusercontent.com/63130724/184128167-c054f4e1-d0df-49c3-b5b9-3efcf40097d5.png)

Thank you!! Loving this card

**Comment by alexarch21** [comment]
The toolbar spacing looks like a rendering issue specific to iOS and possibly the iOS app. The spacing is not supposed to be that way and it isn't on any other platform I tried, including on OSX or on the Android HA app. I don't have an iPhone, so I cannot test or debug it on that platform.

On Android, the spacing looks like this (and that's the way it's supposed to look):
![image](https://user-images.githubusercontent.com/60828821/185942839-3630a178-9cf0-4cb1-8cc5-c2217cc83a65.png)

Did you try it on iOS Safari ? 

The horizontal label spacing can be adjusted in the YAML, as described in the Readme under [Changing the UI layout](https://github.com/alexarch21/history-explorer-card#changing-the-ui-layout).
