### ISSUE TITLE
Separate date and time

### ISSUE THREAD

**Issue by SteveRMann** [alexarch21/history-explorer-card#57]
I know this would break a lot of installations, but I would like to see date and time on separate fields.

**Comment by alexarch21** [comment]
> I know this would break a lot of installations

Typically this raises a big red flag...

> but I would like to see date and time on separate fields.

What do you mean by this ? What fields ?

**Comment by SteveRMann** [comment]
Timestamp is a single field:
2022-08-26 01:18:03,0.8
I would like the option of two fields for the timestamp:
2022-08-26,01:18:03,0.8

**Comment by alexarch21** [comment]
Is this about CSV export ? If yes, just treat the space as an additional delimiter on CSV import in Excel, Calc, etc. It will be split out into a separate column.

There may be CSV export options in the future, but this is nothing that is high priority right now I'm afraid.
