### ISSUE TITLE
Axis on the right

### ISSUE THREAD

**Issue by DaniJulia** [alexarch21/history-explorer-card#63]
Fist of all. Congratulations! By far, the best graph for Home Assistant.
With this said: I would only like to ask if it's possible (or add a vote for it) to print the vertical axis on the right side of the graph.
And last: Do you have any kind of PayPal or something where I can buy you a beer?
Thank you very much!

**Comment by alexarch21** [comment]
Thanks, glad you like the card.

What would the typical use case for switching the axis sides be ? Are we talking about personal preference or do you see another, more general advantage for the switch ? I'm asking because this is non-trivial to implement and would require a not insignificant time investment (it changes the entire card layout).

**Comment by DaniJulia** [comment]
As time values grow from left to right, the most recent and "current" values are on the right side of the graph. Hence, having the axis on the right side would make it much easier to get the idea of such current values, other than jump from one side to the other of the graph to follow the lines of the values.
However, even if in my understanding ALL the graphs on the world would make more sense in that way, obviously "I" am the weird one, because no one on the entire planet seems to have this logic... since I never see anyone using graphs like this.
I think that this representation is a misleading heritage from a misunderstanding of historical facts (like the abominable layout of qwerty keyboards, that only had sense in the lack of resources of the first inventor of the typewriting machines...)... long ago... and we keep because most human beings are so hard to "reprogram" once they "learn" something.

With all this said, and even more if you said that this it's not easy task to accomplish; I completely agree that for sure doesn't worth spending any more time dealing with such a "freak" request.
Thank you very much for your answer and especially for your time to accomplish this magnificent card; And for this, my other question about some way to "buy you a beer" still stands.
