### ISSUE TITLE
Background color

### ISSUE THREAD

**Issue by RobertoCravallo** [alexarch21/history-explorer-card#64]
First of all, thank you. Very cool stuff!

I am pretty new to HA and like your component very much!! For the life of me, I can't figure out how to set the background-color for the graph. I am using a dark theme, without a light option. So I really would like to set the background of the graph to grey or white or some light color. Is this possible?

Regards from Germany,

Robert

**Comment by alexarch21** [comment]
The card does not set a background color at all, that's the job of the HA theme. The graphs background is basically transparent and the HA theme background shines through. Right now there is no way to explicitly set the background color for graphs. The idea behind using a dark theme is that all backgrounds are dark after all :) Do you have problems seeing the graphs or the grid lines on the dark background ? If so, you can explicitly set the colors of those (see [Customizing the color of UI elements](https://github.com/alexarch21/history-explorer-card#customizing-the-color-of-ui-elements)).

If you really want to change the background color, you could use a custom component like card mod to manipulate the page CSS and insert a `background-color` tag for the graphs. Depending on the theme you use, the results may look strange.
