### ISSUE TITLE
Inverted plus/minus logic in the duration

### ISSUE THREAD

**Issue by denilsonsa** [alexarch21/history-explorer-card#66]
This card allows the user to change the duration of the graph. It even shows `+` and `-` buttons for quick toggling:

![screenshot showing "1 day" duration and the + and - buttons](https://user-images.githubusercontent.com/121676/194154862-2a6bfe9f-f4eb-4f00-b06e-24406f71b577.png)

So, if it's showing "1 day" and I press `+`, what do I expect? I expect it to increase, possibly to 2 days. Instead, the logic is reversed: it reduces to 12 hours. Similarly, when pressing `-` I would expect the duration to decrease, but it actually increases.

Maybe those symbols were chosen while thinking about zoom+ and zoom-. However, we already have a zoom button, so those symbols intuitively mean something else.

My suggestion is to just reverse the logic, so that `+` increases the duration and `-` decreases it.

**Comment by alexarch21** [comment]
```
uiLayout:
  invertZoom: true
```

See [this issue](https://github.com/alexarch21/history-explorer-card/issues/34) for more info on why / how / etc if you're curious. For some reason that option flew under the radar and didn't make it in the readme.
