### ISSUE TITLE
Single series focus

### ISSUE THREAD

**Issue by eggman0131** [alexarch21/history-explorer-card#67]
Any chance of adding the ability to double-click or long-click an entity in the legend and have it become the only active series.  This would help where you have a lot of series, and need to focus on one for a time.

**Comment by alexarch21** [comment]
Sadly the history explorer card has been declared end of life and won't be developed anymore. So I will have to close this issue / FR without resolution. This repository will be archived and set to read-only shortly.

See this post on the HA forum for more information: 

https://community.home-assistant.io/t/new-interactive-history-explorer-custom-card/369450/978
