### ISSUE TITLE
Adding options to fill and/or color 

### ISSUE THREAD

**Issue by HermesHonshappo** [alexarch21/history-explorer-card#70]
Hello.  Thanks for this awesome development. I think I'm using at leat a dozen of them on my HA

Would it be feasible and not too time consuming to be able to change the line color or bar color, or the fill color based on a value?
Use cases:
 - displaying energy bars, they could start as green and turn to red when above 5kWh
 - displaying temperatures, they could be blue below 10°C, red above 30 and green in between
 - fill color could be changed depending on another sensor. The fill color on a temperature sensor could then be used to display when a thermostat is in "heating" vs "idle" mode for example). Or a water heater status could fill a power usage in red when it is heating.

Maybe this is already feasible with some scripting, but I am not savvy enough to see if that's the case.

**Comment by alexarch21** [comment]
Right now this is not supported. But I can see this being useful for visualizing value ranges, so I'll mark this as an enhancement request.

Your third point however, coloring by other entities, is unlikely to be implemented anytime soon. It requires fetching multiple entities from the database for use in a single time series graph. Supporting that would require significant changes to the data management architecture of the card.

**Comment by alexarch21** [comment]
This is now possible for bar charts in V1.0.28. See [color-ranges](https://github.com/alexarch21/history-explorer-card#color-ranges).

**Comment by leonardpitzu** [comment]
Is this also possible on a line chart? Like having a temperature chart - lower part of the chart (0-15 Celsius) shall be blue, middle part (16-22 Celsius) shall be yellow and upper part (23-... Celsius) shall be red.
