### ISSUE TITLE
Explorer Card shows no Data

### ISSUE THREAD

**Issue by ilu2k21** [alexarch21/history-explorer-card#72]
installed it via HACS, HA in a Docker Container.
when i choose an entitiy no data is being displayed.

Any hints on this?

**Comment by alexarch21** [comment]
I'm afraid not without more details. Post your logs to begin with.

**Comment by ilu2k21** [comment]
Sorry for the question, are there more than the homeassistant.log?

**Comment by alexarch21** [comment]
For the purpose of this card, any error should be reported in the homeassistant log.

**Comment by ilu2k21** [comment]
searched the log, it shows no error regarding history card explorer
![Bildschirmfoto 2022-10-21 um 09 44 34](https://user-images.githubusercontent.com/78492525/197141463-1e189c82-5ded-416e-b6cc-cdedd088db96.png)
This is a picture how the card looks

**Comment by alexarch21** [comment]
You did hit the add button (the plus sign next to the name), right ?

**Comment by ilu2k21** [comment]
yes, was this wrong?

**Comment by alexarch21** [comment]
No that was fine. Did you check the logs **after** clicking the button ? 

Please check:

- Make sure the entity_id is spelt correctly and actually exists within HA. Check in the developer settings and post a screenshot of the entity in there with all its attributes.
- Post  your YAML config for the card

**Comment by ilu2k21** [comment]
Got it working now, tried the sample config from the readme. Thougt it would work by just selecting the entity.
Thanks for helping, and good work with the card!!

**Comment by alexarch21** [comment]
Yes, normally it does work by selecting the entity in the dropdown and then pressing the add button.

Anyway, great you got it to work.
