### ISSUE TITLE
FR: Day selector 

### ISSUE THREAD

**Issue by Andreas2430** [alexarch21/history-explorer-card#75]
Hi, thanks for the History Explorer card, it works nicely for me. 

This is a feature request: Sometimes I would like to use the HE card to go back to a certain date. 

To do this, currently I set the time range to 1 day and then click the left button until I reach that day. 

This can take some time, therefore it would be nice to have a day selector, similar to how you can select the time in Home Assistant's standard history viewer.

**Comment by alexarch21** [comment]
Sadly the history explorer card has been declared end of life and won't be developed anymore. So I will have to close this issue / FR without resolution. This repository will be archived and set to read-only shortly.

See this post on the HA forum for more information: 

https://community.home-assistant.io/t/new-interactive-history-explorer-custom-card/369450/978
