### ISSUE TITLE
HIgher resolution on timestamps?

### ISSUE THREAD

**Issue by larrybarello** [alexarch21/history-explorer-card#79]
I would like to integrate some data in Excel, but the CVS export timestamps only resolve to minute values, so I get a lot of deltas of 0. Not so good.

I took a couple stabs at formatting the timestamp and all failed.  Either HA doesn't support it, or I am clueless (most likely).

**Comment by alexarch21** [comment]
The card doesn't touch the data, it's the raw data from the database. It just formats it and the default formatting includes a seconds field, like for example **2022-10-24 00:00:00**. Does your export include that seconds field ? If not, then something is wrong with your formatting string. In that case I suggest removing your custom time format and use the default one. 

If the seconds appear but are always zero, then that is what is stored in your database.

**Comment by larrybarello** [comment]
I looked at my entries again and again and finally got the format to work and got seconds out.  All dyslexic typos. Thanks for the reply.  The card is very  nice.   Larry From: AlexSent: Sunday, October 23, 2022 6:29 PMTo: alexarch21/history-explorer-cardCc: larry Barello; AuthorSubject: Re: [alexarch21/history-explorer-card] HIgher resolution on timestamps? (Issue #79) The card doesn't touch the data, it's the raw data from the database. It just formats it and the default formatting includes a seconds field, like for example 2022-10-24 00:00:00. Does your export include that seconds field ? If not, then something is wrong with your formatting string. In that case I suggest removing your custom time format and use the default one.If the seconds appear but are always zero, then that is what is stored in your database.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
