### ISSUE TITLE
 Chart size when the card is reduced

### ISSUE THREAD

**Issue by Bellavista** [alexarch21/history-explorer-card#8]
Hi, best work
i found this problem, when i resize the column card the graph goes out
thanks for your work
![image](https://user-images.githubusercontent.com/46230198/151250998-d20cd0fe-9762-4e7e-a1d5-5fefba4df2fa.png)

**Comment by alexarch21** [comment]
Did you try simply refreshing the page ?

**Comment by alexarch21** [comment]
Fixed in V1.0.15.
