### ISSUE TITLE
FR: option to sync bar time period across bar graphs

### ISSUE THREAD

**Issue by rct** [alexarch21/history-explorer-card#80]
Bar graphs have the feature of a time period (aggregation) per bar selector on each graph.  I’d like to have the option have a single selector for multiple bar graphs in a card so they are all showing hourly, daily, …

Example use case: creat a better energy consumption monitoring graph that can easily be switched.

**Comment by alexarch21** [comment]
Unfortunately this won't be on the cards roadmap for the foreseeable future. Sorry.
