### ISSUE TITLE
similar entities as columns when exporting csv

### ISSUE THREAD

**Issue by thibaultmol** [alexarch21/history-explorer-card#82]
For ex, I have a graph with the 3 different votlages of our grid. When I export a csv of this, I kinda expected a csv with 3 data columns. And not just all of them each a newline.

![Screenshot_590](https://user-images.githubusercontent.com/1010226/199981424-56f8b1eb-3a65-40ba-9dc3-23164b3bde4e.png)

![Screenshot_591](https://user-images.githubusercontent.com/1010226/199981463-bc5ae36c-6401-4ce1-ab1e-1597fb849ab3.png)

**Comment by alexarch21** [comment]
Having entities with the same unit of measure is not enough for this to work. The entities would all need to be exactly synchronized, with their samples taken exactly at the same timecode. And the exporter would need to know that before exporting, so it would have to run a prior analysis on the data.

Doing this in Excel or LibreOffice is basically a two click copy and paste operation.

So I think this is too much of a nice use at this time and there's an easy workaround. Maybe in the future as more CSV export options may be added over time.

**Comment by thibaultmol** [comment]
You bring up a fair point, but counter point: what if the entities are all from the same device. In a lot of cases, they would have the same timings. In my example, a power meter that shows the voltage of each of it's 3 phases. I checked, their timings are exactly the same (cause I assume that it just sends all entities data in one bulk message to HA)

**Comment by alexarch21** [comment]
I understand, but this is really too specific to your setup. It's already a very specific case, pretty much only applicable to multi phase power measurements, which are not very common and we can't rely on the fact that all values are perfectly sync'ed. In my setup, for example, the measurements for the 3 phases come in sequentially, offset by a few milliseconds. And that's where the problems start, the exporter would have to start guessing on how to group them or start interpolating. And as mentioned, if they are in fact perfectly aligned in your case, then this is just a matter of copy and pasting the columns in Excel.
