### ISSUE TITLE
FR : Monthly group by and custom group by period

### ISSUE THREAD

**Issue by o0larrylurex0o** [alexarch21/history-explorer-card#83]
Hi, thx for your awesome work.

Since, many graph card, including HA energy dashboard cannot do it.
Maybe you could :)

The idea would be to be possible to select a custom "group by" period, that could be used to display billing for energy.

For example my gaz provider bills me from the 9th to the 8th.
This should be available for statistics data.

So we could have a bar chart for each month over a year

thx a lot

**Comment by alexarch21** [comment]
Monthly is available now. But the offset won't make it I'm afraid. This would create too many issues with sync'ing other graphs that are displayed at the same time in the graph list, when the time references do not match anymore with the offset. Sorry for that.
