### ISSUE TITLE
water_heater temperature not shown

### ISSUE THREAD

**Issue by ARNik** [alexarch21/history-explorer-card#84]
If I add water_heater entity, it is not showing the temperature.
![image](https://user-images.githubusercontent.com/3407744/200740462-0d0bd1a6-abfd-41ff-8705-d11121ca8500.png)

When I use original history:
![image](https://user-images.githubusercontent.com/3407744/200740694-2c11d171-ed77-4372-880e-de35167f36da.png)

**Comment by alexarch21** [comment]
Impossible to say with so little information.

**Comment by barbaraBrzozka** [comment]
I have a similar issue with thermostatic valve. The "current" and "target" temperatures are attributes of "climate" entity. Many other attributes of this "climate" entity are also visible as separate entities (of type number, binary_sensor, switch...) and can be selected for plot, but those two -- aren't.

**Comment by alexarch21** [comment]
This card does not support attributes (and never will). If you want to visualize attributes, you'll have to use a template sensor that exposes the attribute as an entity.
