### ISSUE TITLE
replaces itself in the "more-info" dialog

### ISSUE THREAD

**Issue by SinisterMedusa** [alexarch21/history-explorer-card#85]
The last version replaces itself in the "more-info" dialog, this should be user controlled in my opinion.
I personally like it, but this card makes absolutely no sense to show history of "climate.*" entities.

**Comment by alexarch21** [comment]
It replaces that dialog only if you turned it on.

Turn it off if you don't like the replacement.

**Comment by SinisterMedusa** [comment]
OK, how do I turn it off?
Is there also a way to enable/disable it per domain or per entity?

**Comment by alexarch21** [comment]
You can't specify this per entity. It's an all or nothing thing. If you don't like the override, you'll have to turn it off entirely (or not turn it on in the first place).

**Comment by SinisterMedusa** [comment]
OK, thanks, how do I turn it off?

**Comment by alexarch21** [comment]
![image](https://user-images.githubusercontent.com/60828821/201123411-0f6808a7-2275-4846-905c-d8b2c0e9461a.png)
