### ISSUE TITLE
stateColors in infoPanel causes error, no chart loads in info panel.

### ISSUE THREAD

**Issue by j4c3** [alexarch21/history-explorer-card#86]
After adding stateColors under the infoPanel level, the info panel chart no longer loads.  I see the chart header (with empty date, and < 1 H for time values.)  Using HISTORY-EXPLORER-CARD  Version 1.0.34.  Same behavior in 1.0.32 and 33. 

The console displays the following error:

history-explorer-card.js:76 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'pconfig')
    at e._injectHistoryExplorer (history-explorer-card.js:76:8206)
    at e._hec_updated (history-explorer-card.js:76:10965)
    at c._$AE (styles.ts:371:1)
    at c.performUpdate (styles.ts:371:1)
    at c.scheduleUpdate (styles.ts:371:1)
    at c._$EC (styles.ts:371:1)

I tried using off: blue (saving this replaces it as 'off': blue) door.off: blue, and door.off: rgb(255, 165, 1).  I also tried removing entityOptions:, so I just had the stateColors section, but none of these made a difference. 

This is a very cool addition!  Let me know if there is anything else you'd like for me to try.

**Comment by alexarch21** [comment]
OK, fixed. Thanks for reporting. Will be in the next version.

**Comment by alexarch21** [comment]
Fixed in V1.0.35
