### ISSUE TITLE
Infopanel labels are clipped

### ISSUE THREAD

**Issue by TimoJJ** [alexarch21/history-explorer-card#87]
Long values are not show fully, left side is clipped. No issues with normal HE cards or original HA entity cards. Using HE 1.0.34.
Windows 10 
Edge browser
Home Assistant 2022.11.2
Supervisor 2022.10.2
Operating System 9.3
Frontend 20221108.0
.
![clipped](https://user-images.githubusercontent.com/63199895/201052075-8b3236b5-342b-476e-ab3f-49dba813db50.png)

**Comment by alexarch21** [comment]
Fixed in V1.0.36.
