### ISSUE TITLE
FR: Second Y-Axis?

### ISSUE THREAD

**Issue by dxmnkd316** [alexarch21/history-explorer-card#88]
First, this is a _really_ spectacular card.  It's what the built-in stats cards need to be.  The multiple ways to zoom, select, display, etc.  Fantastic stuff.

One addition would make this nearly perfect.  Secondary y-axis.  I'm basically trying to recreate the settings for the climate templates where it will show when your hvac system is on heat or cool.  But, I can't find a way to make the HE card or Home Assistant to respect the null values I have attempted to assign when the heating system isn't running.  So anyways, the second y-axis would help solve that issue because I'd be able to move those series to a separate scale and not have to worry about it.

Thanks and cheers

<img src="https://user-images.githubusercontent.com/46753733/201359547-82555f10-c561-43d6-9888-7023517f566a.png" data-canonical-src="https://user-images.githubusercontent.com/46753733/201359547-82555f10-c561-43d6-9888-7023517f566a.png" width="50%" height="50%" />
vs. 
<img src="https://user-images.githubusercontent.com/46753733/201359752-02d887a4-54f3-48fa-b652-565b7c1628a0.png" data-canonical-src="https://user-images.githubusercontent.com/46753733/201359752-02d887a4-54f3-48fa-b652-565b7c1628a0.png" width="50%" height="50%" />

Essentially, this is what I'm trying to replicate from the history-graph card.
![image](https://user-images.githubusercontent.com/46753733/201359964-e048e58b-4b26-48a0-aea5-59f94e5b4a78.png)

**Comment by rct** [comment]
This is something I'd love to see as well. I use the climate entities in the history graph a lot for HVAC and other things (hot tub heating)

**Comment by alexarch21** [comment]
To be honest, a second Y axis is unlikely to be added anytime soon. It's a lot of work, I don't have a lot of free time these days and it doesn't seem to be a very commonly used feature. Maybe a specific mode for climate entities would be more appropriate.

That said, I think there would be other ways to reach the result. I'm not sure I understand what your issue currently is. What exactly do you mean by '_But, I can't find a way to make the HE card or Home Assistant to respect the null values I have attempted to assign when the heating system isn't running_' ?

**Comment by ImagineerNL** [comment]
My usecase is for temperature and humidity to be shown in 1 graph.
I have 6 sensors in different locations; having all temperatures in one and all humidity in one isnt helping, as I have a card per room.
Being able to combine them in one card is the most pleasing route for me.

A workaround for me that has that functionality is currently the [Mini Graph Card](https://github.com/kalkih/mini-graph-card), but your card is sooo much more than that.
Maybe the source of that card can give you some insight if theres an easy route to implement it.

Nevertheless, awesome add-on what you currently have built!
Thanks for your hard work so far.

**Comment by alexarch21** [comment]
It's not that I don't know how to do it. It's that I don't have the time to do it.

**Comment by ImagineerNL** [comment]
Understood. Thanks for your time.

**Comment by dxmnkd316** [comment]
> To be honest, a second Y axis is unlikely to be added anytime soon. It's a lot of work, I don't have a lot of free time these days and it doesn't seem to be a very commonly used feature. Maybe a specific mode for climate entities would be more appropriate.

Totally fair and understandable.  I might fork this and see what I can do with it as well.  Figured i'd throw it out there and see what the possibility of this being added would be.

> 
> That said, I think there would be other ways to reach the result. I'm not sure I understand what your issue currently is. What exactly do you mean by '_But, I can't find a way to make the HE card or Home Assistant to respect the null values I have attempted to assign when the heating system isn't running_' ?

I created a sensor that when the hvac_action attribute for my ecobee thermostat is set to "heating", it records the current temperature of the house as calculated by the ecobee.  Otherwise, if the hvac_action is _not_ "heating" it would send a null value to the sensor.  (This could be part of my problem, but it's the only way I could get this to sort of work.)

It's a way of duplicating the way climate devices/sensors show up on the built-in history graph card (the orange fill).  The history graph card takes the temperature and fills below that temperature with the orange, but it doesn't reset the y-axis minimum to zero.  The remaining series (bedroom, living room, etc.) are what determine the minimum on the y-axis.  So if you look at the first two pictures, the difference is the y-axis is showing a min of 0 on the first and 60 on the second.  Same with the third image, 60 F min.

So the issue I seem to be having is that the HE card is setting some of the null values to zero.  Here's what I mean:
<img src="https://user-images.githubusercontent.com/46753733/202290790-d20dafff-a526-45f9-ad8a-bba407476cad.png" data-canonical-src="https://user-images.githubusercontent.com/46753733/202290790-d20dafff-a526-45f9-ad8a-bba407476cad.png" width="50%" height="50%" />

And here's what the data is within my historian
<img src="https://user-images.githubusercontent.com/46753733/202472789-97707660-e432-425c-85f7-300e82382cf2.png" data-canonical-src="https://user-images.githubusercontent.com/46753733/202472789-97707660-e432-425c-85f7-300e82382cf2.png" width="50%" height="50%" />

Maybe there's a better way to do the sensor and record the data, but I'm still somewhat new to HA, so I'm still learning.

**Comment by dxmnkd316** [comment]
> It's not that I don't know how to do it. It's that I don't have the time to do it.
> 
> This card wasn't ever meant to be a general purpose graphing card, replacing the mini graph card or similar (eventhough a lot of people use it that way now). First and foremost, this is a card for visualizing the history for debugging and analysis purposes. Visual bells and whistles are not that high up the priority list, as the time I can spend on this project is pretty limited sadly. I'll leave this FR open, maybe I might get to it if I find some time eventually.

Thanks for the time you've already put into this.  No expectation of future work in even the most remote sense.  Only thanks for sharing some of your hard work with the world.

**Comment by alexarch21** [comment]
Ok, I see what you're after. No, null is not a valid value for a line graph that is based on numeric values. Depending on the implementations, some may simply ignore it (apparently the native history graph does), some may interpret it as a number or even interpolate over it.

I mean, practically speaking, this is from your indoor sensors, is the temperature ever expected to be below 60 ? Because if not, why not simply put ymin to 60 and leave ymax undefined. Wouldn't that replicate what you had in mind ?

**Comment by alexarch21** [comment]
I'm going to close this issue, as the original FR (second Y axis) is unlikely to be implemented anytime soon.

A specific thermostat view, however, is something I'm considering for the future. As a sidenote, since V1.0.41, you can use the `undefined` value for your sensor instead of `null`. It will create a gap in your graph (even if `showUnavailable` is false) and it will not influence the Yaxis auto scale. As far as I can see, this is what your workaround is about.
