### ISSUE TITLE
Unused space if toolbar and selector hidden

### ISSUE THREAD

**Issue by KNXBroker** [alexarch21/history-explorer-card#89]
Hi, first of all thank you for your great card.
If have hidden the toolbars and selectors in my panels, however the place for both elements is still there:  

![image](https://user-images.githubusercontent.com/25910703/201420327-40ef9bb9-1eed-4b40-af3c-20c4c62c3915.png)

Is it possible to hide the complete  addUIHtml block if not required? Thank you!

**Comment by alexarch21** [comment]
Yep, that's a bug :) Will be fixed in next release.

**Comment by alexarch21** [comment]
Fixed in V1.0.35.

**Comment by KNXBroker** [comment]
Thank you
