### ISSUE TITLE
no issue but implementation for more space

### ISSUE THREAD

**Issue by Bellavista** [alexarch21/history-explorer-card#9]
Is it possible to hide the measurement unit? 
Is it possible ti hide the title or change the text ?
Can you add this option?
So you can have more space for graph
![image](https://user-images.githubusercontent.com/46230198/151250538-df477784-71cd-461b-9846-072aeebc66b4.png)
Thank for your work

**Comment by alexarch21** [comment]
The title can be hidden / changed by using the `header` property in the YAML. See the advanced example down at the bottom of the Readme.

**Comment by Bellavista** [comment]
it work!
header: '  ' or header: [] work to hide, 
header: Pippo to change the text
Good

**Comment by alexarch21** [comment]
Good. I'll see what I can do about the space. Maybe make it configurable.

**Comment by alexarch21** [comment]
You can now remove the labels and / or resize the label area in V1.0.14. See the readme under **Changing the UI layout**.

Don't make the label area too small or it will hide the ticks on the Y axis.

**Comment by Bellavista** [comment]
Good enhancement
