### ISSUE TITLE
Add "ShowTooltipEntityLine" option?

### ISSUE THREAD

**Issue by jerrm** [alexarch21/history-explorer-card#90]
I'm late to the party, but this is a phenomenal work!

As maybe too much of an OCD minimalist, one small option I'd like to see is the ability to omit the entity name from the tooltip. On single entity graphs and infopanels it is redundant.  Even on multi-entity graphs the "color" is often enough.

**Comment by alexarch21** [comment]
I agree that this would be a useful option.

**Comment by alexarch21** [comment]
Added to V1.0.36.
```
type: custom:history-explorer-card
tooltip:
  showLabel: false
```
