### ISSUE TITLE
Incorrect defaultTimeRange showing in graph 

### ISSUE THREAD

**Issue by blamaz** [alexarch21/history-explorer-card#93]
When selecting any period longer than 3 weeks for the defaultTimeRange, UI show 3 months.
Strangely, if I input 340 to 500 hours as a defaultTimeRange it's giving me a 1 month period.

Thank again for this great card

![Screenshots1](https://user-images.githubusercontent.com/33003276/201982944-73e5dd1f-b57c-4d7c-bce2-a13be06e0c73.jpg)

![Screenshots2](https://user-images.githubusercontent.com/33003276/201983286-5ced00d3-e5d6-4f23-ab39-3f133f4a0731.jpg)

**Comment by alexarch21** [comment]
Yeah that's strange, it should jump to 1 month, which is the next valid range. As a workaround, specify the range as hours (as you did).

**Comment by blamaz** [comment]
No problem, after some testing I find it illogical as 335 hours is just under 2 weeks time. Maybe the following numbers can help you otherwise everything is working fine as it is. I did try changing my UI language to english but the results were the sames.
335 hours gave me 3 weeks
336 hours gave me 2 weeks
337 up to 503 hours gave me 1 month
504 hours gave me 3 weeks
505 hours up to 719 gave me 3 months
720 hours gave me 1 month
721 up to (not tested) gave me 6 months

Have a nice day

**Comment by alexarch21** [comment]
Improved in V1.0.37. You can now also use `o` for months or `y` for year. This version now supports a maximum displayable time range of up to one year.
