### ISSUE TITLE
Hide interval selector on bar-chart

### ISSUE THREAD

**Issue by DIY62** [alexarch21/history-explorer-card#95]
Good afternoon,

Is there a possibility to hide the interval-selector on the bar chart?

I have the following code and it seems to be impossible to hide this selector:

<img width="488" alt="screenprint code" src="https://user-images.githubusercontent.com/95056292/202853507-2de90190-e7ae-4df2-99b6-79592864d73b.png">
<img width="392" alt="screenprint" src="https://user-images.githubusercontent.com/95056292/202853341-68ee4b3e-0497-4d3e-b111-74ede16fd7cc.png">

Thank you in advance

Emanuel

**Comment by alexarch21** [comment]
No you can't hide it at this time

**Comment by DIY62** [comment]
Ok, I hope it will be possible in the future.

Thanks for your reply.

**Comment by alexarch21** [comment]
You can use something like card mod to remove it in the mean time.

**Comment by alexarch21** [comment]
The interval selector can now be hidden in V1.0.38
```
uiLayout:
  interval: hide
```

**Comment by DIY62** [comment]
Thanks @alexarch21 , looks perfect 👍🏼

<img width="387" alt="screenshot 2022-11-26" src="https://user-images.githubusercontent.com/95056292/204107329-8cbeb42f-ad8d-49b1-bfa5-b4afaf2354b3.png">
