### ISSUE TITLE
How to get legend in the chart itself?

### ISSUE THREAD

**Issue by oywino** [alexarch21/history-explorer-card#96]
Is it possible to have the legends in the graph (chart) itself, and not just as a row on top of the chart?

**Comment by alexarch21** [comment]
What do you mean by in the chart itself ?

**Comment by oywino** [comment]
Here's an example:
![image](https://user-images.githubusercontent.com/18447119/202864578-38789951-967f-42a9-b201-1d93ed6d5c61.png)

**Comment by alexarch21** [comment]
I'm afraid this is neither possible nor planned.

**Comment by oywino** [comment]
Not possible? Everything is possible!
Not planned - I guess I have to accept that.
But it's too bad. As it is now, it's very hard to use the graph as a reporting tool. It serves a 'nice to have' purpose, only.
