### ISSUE TITLE
Feature request: filterEntities: 'binary_sensor.*' 'sensor.*_device_temperature*'

### ISSUE THREAD

**Issue by roykrikke** [alexarch21/history-explorer-card#98]
First off what a great add-on. Thank you for your commitment to making this possible.

I have a feature request, it would be cool if we could config multiple filters e.g.:
`filterEntities: 'binary_sensor.*' 'sensor.*_device_temperature*'`
or
`
filterEntities: 'binary_sensor.*'
filterEntities: 'sensor.*_device_temperature*'
`

**Comment by alexarch21** [comment]
Sounds like a good idea !

**Comment by alexarch21** [comment]
Added to V1.0.41.

Syntax for multiple filters is a YAML list:
```
type: custom:history-explorer-card
filterEntities:
  - 'binary_sensor.*'
  - 'sensor.*_device_temperature*'
```

**Comment by roykrikke** [comment]
Wow, thanks for implementing this! Keep up the good work!
